// ---------- EN <-> AR (Arabic) ----------
const DICT_EN_AR = [
  { en: "hello", ar: "مرحبا" },
  { en: "hi", ar: "أهلا" },
  { en: "good morning", ar: "صباح الخير" },
  { en: "good evening", ar: "مساء الخير" },
  { en: "good night", ar: "تصبح على خير" },
  { en: "goodbye", ar: "وداعا" },
  { en: "bye", ar: "مع السلامة" },
  { en: "please", ar: "من فضلك" },
  { en: "thank you", ar: "شكرا" },
  { en: "thanks", ar: "شكرا" },
  { en: "you're welcome", ar: "عفوا" },
  { en: "sorry", ar: "آسف" },
  { en: "excuse me", ar: "عفوا" },
  { en: "yes", ar: "نعم" },
  { en: "no", ar: "لا" },
  { en: "okay", ar: "حسنا" },
  { en: "ok", ar: "حسنا" },
  { en: "i", ar: "أنا" },
  { en: "you", ar: "أنت" },
  { en: "he", ar: "هو" },
  { en: "she", ar: "هي" },
  { en: "we", ar: "نحن" },
  { en: "they", ar: "هم" },
  { en: "me", ar: "إياي" },
  { en: "my", ar: "ملكي" },
  { en: "your", ar: "ملكك" },
  { en: "what", ar: "ماذا" },
  { en: "where", ar: "أين" },
  { en: "when", ar: "متى" },
  { en: "why", ar: "لماذا" },
  { en: "who", ar: "من" },
  { en: "how", ar: "كيف" },
  { en: "how much", ar: "كم" },
  { en: "how many", ar: "كم" },
  { en: "which", ar: "أي" },
  { en: "is", ar: "هو" },
  { en: "are", ar: "هم" },
  { en: "am", ar: "أنا" },
  { en: "have", ar: "لدي" },
  { en: "has", ar: "لديه" },
  { en: "do", ar: "افعل" },
  { en: "does", ar: "يفعل" },
  { en: "go", ar: "اذهب" },
  { en: "come", ar: "تعال" },
  { en: "see", ar: "انظر" },
  { en: "look", ar: "انظر" },
  { en: "hear", ar: "اسمع" },
  { en: "listen", ar: "استمع" },
  { en: "say", ar: "قل" },
  { en: "speak", ar: "تكلم" },
  { en: "talk", ar: "تحدث" },
  { en: "know", ar: "أعرف" },
  { en: "think", ar: "أفكر" },
  { en: "want", ar: "أريد" },
  { en: "need", ar: "أحتاج" },
  { en: "like", ar: "أحب" },
  { en: "love", ar: "أحب" },
  { en: "hate", ar: "أكره" },
  { en: "eat", ar: "كل" },
  { en: "drink", ar: "اشرب" },
  { en: "sleep", ar: "نم" },
  { en: "work", ar: "عمل" },
  { en: "play", ar: "العب" },
  { en: "buy", ar: "اشتر" },
  { en: "sell", ar: "بع" },
  { en: "give", ar: "أعط" },
  { en: "take", ar: "خذ" },
  { en: "make", ar: "اصنع" },
  { en: "help", ar: "ساعد" },
  { en: "ask", ar: "اسأل" },
  { en: "answer", ar: "أجب" },
  { en: "find", ar: "جد" },
  { en: "open", ar: "افتح" },
  { en: "close", ar: "أغلق" },
  { en: "start", ar: "ابدأ" },
  { en: "stop", ar: "توقف" },
  { en: "live", ar: "اعيش" },
  { en: "die", ar: "مت" },
  { en: "kill", ar: "اقتل" },
  { en: "run", ar: "اركض" },
  { en: "walk", ar: "امش" },
  { en: "read", ar: "اقرأ" },
  { en: "write", ar: "اكتب" },
  { en: "learn", ar: "تعلم" },
  { en: "teach", ar: "علم" },
  { en: "understand", ar: "أفهم" },
  { en: "remember", ar: "تذكر" },
  { en: "forget", ar: "انس" },
  { en: "believe", ar: "أؤمن" },
  { en: "feel", ar: "أشعر" },
  { en: "man", ar: "رجل" },
  { en: "woman", ar: "امرأة" },
  { en: "boy", ar: "ولد" },
  { en: "girl", ar: "بنت" },
  { en: "child", ar: "طفل" },
  { en: "children", ar: "أطفال" },
  { en: "baby", ar: "رضيع" },
  { en: "father", ar: "أب" },
  { en: "mother", ar: "أم" },
  { en: "son", ar: "ابن" },
  { en: "daughter", ar: "ابنة" },
  { en: "brother", ar: "أخ" },
  { en: "sister", ar: "أخت" },
  { en: "friend", ar: "صديق" },
  { en: "friends", ar: "أصدقاء" },
  { en: "family", ar: "عائلة" },
  { en: "people", ar: "ناس" },
  { en: "name", ar: "اسم" },
  { en: "house", ar: "بيت" },
  { en: "home", ar: "بيت" },
  { en: "water", ar: "ماء" },
  { en: "fire", ar: "نار" },
  { en: "sun", ar: "شمس" },
  { en: "moon", ar: "قمر" },
  { en: "sky", ar: "سماء" },
  { en: "rain", ar: "مطر" },
  { en: "food", ar: "طعام" },
  { en: "bread", ar: "خبز" },
  { en: "meat", ar: "لحم" },
  { en: "milk", ar: "حليب" },
  { en: "tea", ar: "شاي" },
  { en: "coffee", ar: "قهوة" },
  { en: "money", ar: "مال" },
  { en: "book", ar: "كتاب" },
  { en: "car", ar: "سيارة" },
  { en: "time", ar: "وقت" },
  { en: "day", ar: "يوم" },
  { en: "night", ar: "ليل" },
  { en: "year", ar: "سنة" },
  { en: "today", ar: "اليوم" },
  { en: "tomorrow", ar: "غدا" },
  { en: "yesterday", ar: "أمس" },
  { en: "good", ar: "جيد" },
  { en: "bad", ar: "سيئ" },
  { en: "big", ar: "كبير" },
  { en: "small", ar: "صغير" },
  { en: "new", ar: "جديد" },
  { en: "old", ar: "قديم" },
  { en: "hot", ar: "حار" },
  { en: "cold", ar: "بارد" },
  { en: "fast", ar: "سريع" },
  { en: "happy", ar: "سعيد" },
  { en: "sad", ar: "حزين" },
  { en: "angry", ar: "غاضب" },
  { en: "tired", ar: "متعب" },
  { en: "beautiful", ar: "جميل" },
  { en: "ugly", ar: "قبيح" },
  { en: "rich", ar: "غني" },
  { en: "poor", ar: "فقير" },
  { en: "strong", ar: "قوي" },
  { en: "weak", ar: "ضعيف" },
  { en: "easy", ar: "سهل" },
  { en: "hard", ar: "صعب" },
  { en: "right", ar: "صحيح" },
  { en: "wrong", ar: "خطأ" },
  { en: "true", ar: "صحيح" },
  { en: "false", ar: "خاطئ" },
  { en: "many", ar: "كثير" },
  { en: "more", ar: "أكثر" },
  { en: "all", ar: "الكل" },
  { en: "some", ar: "بعض" },
  { en: "very", ar: "جدا" },
  { en: "and", ar: "و" },
  { en: "or", ar: "أو" },
  { en: "but", ar: "لكن" },
  { en: "because", ar: "لأن" },
  { en: "so", ar: "لذلك" },
  { en: "if", ar: "إذا" },
  { en: "now", ar: "الآن" },
  { en: "here", ar: "هنا" },
  { en: "there", ar: "هناك" },
  { en: "not", ar: "ليس" },
  { en: "only", ar: "فقط" },
  { en: "again", ar: "مرة أخرى" },
  { en: "always", ar: "دائما" },
  { en: "never", ar: "أبدا" },
  { en: "maybe", ar: "ربما" },
  { en: "one", ar: "واحد" },
  { en: "two", ar: "اثنان" },
  { en: "three", ar: "ثلاثة" },
  { en: "four", ar: "أربعة" },
  { en: "five", ar: "خمسة" },
  { en: "six", ar: "ستة" },
  { en: "seven", ar: "سبعة" },
  { en: "eight", ar: "ثمانية" },
  { en: "nine", ar: "تسعة" },
  { en: "ten", ar: "عشرة" },
  { en: "how are you", ar: "كيف حالك" },
  { en: "what is your name", ar: "ما اسمك" },
  { en: "my name is", ar: "اسمي" },
  { en: "i don't know", ar: "لا أعرف" },
  { en: "i love you", ar: "أحبك" },
  { en: "i am hungry", ar: "أنا جائع" },
  { en: "i am tired", ar: "أنا متعب" },
  { en: "see you later", ar: "أراك لاحقا" },
  // profanity
  { en: "fuck", ar: "نيك" },
  { en: "fucking", ar: "لعين" },
  { en: "shit", ar: "خرى" },
  { en: "bitch", ar: "عاهرة" },
  { en: "asshole", ar: "متأنث" },
  { en: "damn", ar: "تبا" },
  { en: "idiot", ar: "أحمق" },
  { en: "stupid", ar: "غبي" },
  { en: "crazy", ar: "مجنون" },
  { en: "bastard", ar: "لقيط" },
  { en: "bullshit", ar: "هراء" },
  { en: "fuck you", ar: "ينيكك" },
  { en: "shut up", ar: "اسكت" },
];

// ---------- EN <-> BN (Bengali) ----------
const DICT_EN_BN = [
  { en: "hello", bn: "হ্যালো" },
  { en: "hi", bn: "হ্যালো" },
  { en: "good morning", bn: "সুপ্রভাত" },
  { en: "good evening", bn: "শুভ সন্ধ্যা" },
  { en: "good night", bn: "শুভ রাত্রি" },
  { en: "goodbye", bn: "বিদায়" },
  { en: "bye", bn: "বিদায়" },
  { en: "please", bn: "অনুগ্রহ করে" },
  { en: "thank you", bn: "ধন্যবাদ" },
  { en: "thanks", bn: "ধন্যবাদ" },
  { en: "sorry", bn: "দুঃখিত" },
  { en: "yes", bn: "হ্যাঁ" },
  { en: "no", bn: "না" },
  { en: "okay", bn: "ঠিক আছে" },
  { en: "ok", bn: "ঠিক আছে" },
  { en: "i", bn: "আমি" },
  { en: "you", bn: "তুমি" },
  { en: "he", bn: "সে" },
  { en: "she", bn: "সে" },
  { en: "we", bn: "আমরা" },
  { en: "they", bn: "তারা" },
  { en: "my", bn: "আমার" },
  { en: "your", bn: "তোমার" },
  { en: "what", bn: "কী" },
  { en: "where", bn: "কোথায়" },
  { en: "when", bn: "কখন" },
  { en: "why", bn: "কেন" },
  { en: "who", bn: "কে" },
  { en: "how", bn: "কীভাবে" },
  { en: "how much", bn: "কত" },
  { en: "is", bn: "হয়" },
  { en: "are", bn: "হয়" },
  { en: "am", bn: "আমি" },
  { en: "have", bn: "আছে" },
  { en: "has", bn: "আছে" },
  { en: "do", bn: "করো" },
  { en: "go", bn: "যাও" },
  { en: "come", bn: "এসো" },
  { en: "see", bn: "দেখো" },
  { en: "look", bn: "দেখো" },
  { en: "say", bn: "বলো" },
  { en: "speak", bn: "কথা বলো" },
  { en: "know", bn: "জানো" },
  { en: "think", bn: "ভাবো" },
  { en: "want", bn: "চাও" },
  { en: "need", bn: "প্রয়োজন" },
  { en: "like", bn: "পছন্দ" },
  { en: "love", bn: "ভালোবাসা" },
  { en: "eat", bn: "খাও" },
  { en: "drink", bn: "পান করো" },
  { en: "sleep", bn: "ঘুমাও" },
  { en: "work", bn: "কাজ" },
  { en: "play", bn: "খেলো" },
  { en: "buy", bn: "কিনো" },
  { en: "give", bn: "দাও" },
  { en: "take", bn: "নাও" },
  { en: "make", bn: "বানাও" },
  { en: "help", bn: "সাহায্য" },
  { en: "ask", bn: "জিজ্ঞাসো" },
  { en: "answer", bn: "উত্তর" },
  { en: "find", bn: "খোঁজো" },
  { en: "open", bn: "খোলো" },
  { en: "close", bn: "বন্ধ করো" },
  { en: "man", bn: "মানুষ" },
  { en: "woman", bn: "মহিলা" },
  { en: "boy", bn: "ছেলে" },
  { en: "girl", bn: "মেয়ে" },
  { en: "child", bn: "শিশু" },
  { en: "father", bn: "বাবা" },
  { en: "mother", bn: "মা" },
  { en: "son", bn: "ছেলে" },
  { en: "daughter", bn: "মেয়ে" },
  { en: "friend", bn: "বন্ধু" },
  { en: "family", bn: "পরিবার" },
  { en: "name", bn: "নাম" },
  { en: "house", bn: "বাড়ি" },
  { en: "home", bn: "বাড়ি" },
  { en: "water", bn: "জল" },
  { en: "fire", bn: "আগুন" },
  { en: "sun", bn: "সূর্য" },
  { en: "moon", bn: "চাঁদ" },
  { en: "sky", bn: "আকাশ" },
  { en: "rain", bn: "বৃষ্টি" },
  { en: "food", bn: "খাবার" },
  { en: "rice", bn: "ভাত" },
  { en: "bread", bn: "রুটি" },
  { en: "milk", bn: "দুধ" },
  { en: "tea", bn: "চা" },
  { en: "money", bn: "টাকা" },
  { en: "book", bn: "বই" },
  { en: "car", bn: "গাড়ি" },
  { en: "time", bn: "সময়" },
  { en: "day", bn: "দিন" },
  { en: "night", bn: "রাত" },
  { en: "year", bn: "বছর" },
  { en: "today", bn: "আজ" },
  { en: "tomorrow", bn: "আগামীকাল" },
  { en: "yesterday", bn: "গতকাল" },
  { en: "good", bn: "ভালো" },
  { en: "bad", bn: "খারাপ" },
  { en: "big", bn: "বড়" },
  { en: "small", bn: "ছোট" },
  { en: "new", bn: "নতুন" },
  { en: "old", bn: "পুরোনো" },
  { en: "hot", bn: "গরম" },
  { en: "cold", bn: "ঠান্ডা" },
  { en: "fast", bn: "দ্রুত" },
  { en: "happy", bn: "খুশি" },
  { en: "sad", bn: "দুঃখিত" },
  { en: "angry", bn: "রাগ" },
  { en: "tired", bn: "ক্লান্ত" },
  { en: "beautiful", bn: "সুন্দর" },
  { en: "rich", bn: "ধনী" },
  { en: "poor", bn: "গরিব" },
  { en: "easy", bn: "সহজ" },
  { en: "hard", bn: "কঠিন" },
  { en: "right", bn: "সঠিক" },
  { en: "wrong", bn: "ভুল" },
  { en: "true", bn: "সত্য" },
  { en: "false", bn: "মিথ্যা" },
  { en: "very", bn: "খুব" },
  { en: "and", bn: "এবং" },
  { en: "or", bn: "বা" },
  { en: "but", bn: "কিন্তু" },
  { en: "because", bn: "কারণ" },
  { en: "so", bn: "তাই" },
  { en: "if", bn: "যদি" },
  { en: "now", bn: "এখন" },
  { en: "here", bn: "এখানে" },
  { en: "there", bn: "সেখানে" },
  { en: "not", bn: "না" },
  { en: "only", bn: "শুধু" },
  { en: "always", bn: "সবসময়" },
  { en: "never", bn: "কখনও না" },
  { en: "maybe", bn: "হয়তো" },
  { en: "one", bn: "এক" },
  { en: "two", bn: "দুই" },
  { en: "three", bn: "তিন" },
  { en: "four", bn: "চার" },
  { en: "five", bn: "পাঁচ" },
  { en: "six", bn: "ছয়" },
  { en: "seven", bn: "সাত" },
  { en: "eight", bn: "আট" },
  { en: "nine", bn: "নয়" },
  { en: "ten", bn: "দশ" },
  { en: "how are you", bn: "তুমি কেমন আছো" },
  { en: "what is your name", bn: "তোমার নাম কী" },
  { en: "my name is", bn: "আমার নাম" },
  { en: "i don't know", bn: "আমি জানি না" },
  { en: "i love you", bn: "আমি তোমাকে ভালোবাসি" },
  { en: "i am hungry", bn: "আমার খিদে লেগেছে" },
  { en: "see you later", bn: "পরে দেখা হবে" },
  // profanity
  { en: "fuck", bn: "চোদ" },
  { en: "shit", bn: "বকবাস" },
  { en: "bitch", bn: "রান্ডি" },
  { en: "asshole", bn: "যাচাই" },
  { en: "damn", bn: "অভিশাপ" },
  { en: "idiot", bn: "বোকা" },
  { en: "stupid", bn: "বোকা" },
  { en: "crazy", bn: "পাগল" },
  { en: "bastard", bn: "হারামি" },
  { en: "bullshit", bn: "বকবাস" },
  { en: "shut up", bn: "চুপ করো" },
];

// ---------- EN <-> PT (Portuguese) ----------
const DICT_EN_PT = [
  { en: "hello", pt: "olá" },
  { en: "hi", pt: "oi" },
  { en: "good morning", pt: "bom dia" },
  { en: "good afternoon", pt: "boa tarde" },
  { en: "good evening", pt: "boa noite" },
  { en: "good night", pt: "boa noite" },
  { en: "goodbye", pt: "adeus" },
  { en: "bye", pt: "tchau" },
  { en: "please", pt: "por favor" },
  { en: "thank you", pt: "obrigado" },
  { en: "thanks", pt: "obrigado" },
  { en: "you're welcome", pt: "de nada" },
  { en: "sorry", pt: "desculpa" },
  { en: "excuse me", pt: "com licença" },
  { en: "yes", pt: "sim" },
  { en: "no", pt: "não" },
  { en: "okay", pt: "ok" },
  { en: "ok", pt: "ok" },
  { en: "i", pt: "eu" },
  { en: "you", pt: "você" },
  { en: "he", pt: "ele" },
  { en: "she", pt: "ela" },
  { en: "it", pt: "isso" },
  { en: "we", pt: "nós" },
  { en: "they", pt: "eles" },
  { en: "me", pt: "me" },
  { en: "my", pt: "meu" },
  { en: "your", pt: "seu" },
  { en: "his", pt: "seu" },
  { en: "her", pt: "sua" },
  { en: "our", pt: "nosso" },
  { en: "their", pt: "seu" },
  { en: "this", pt: "isto" },
  { en: "that", pt: "isso" },
  { en: "what", pt: "o que" },
  { en: "where", pt: "onde" },
  { en: "when", pt: "quando" },
  { en: "why", pt: "por que" },
  { en: "who", pt: "quem" },
  { en: "how", pt: "como" },
  { en: "how much", pt: "quanto" },
  { en: "how many", pt: "quantos" },
  { en: "which", pt: "qual" },
  { en: "is", pt: "é" },
  { en: "are", pt: "são" },
  { en: "am", pt: "sou" },
  { en: "was", pt: "era" },
  { en: "were", pt: "eram" },
  { en: "be", pt: "ser" },
  { en: "have", pt: "ter" },
  { en: "has", pt: "tem" },
  { en: "had", pt: "tinha" },
  { en: "do", pt: "fazer" },
  { en: "does", pt: "faz" },
  { en: "did", pt: "fez" },
  { en: "go", pt: "ir" },
  { en: "goes", pt: "vai" },
  { en: "went", pt: "foi" },
  { en: "come", pt: "vir" },
  { en: "comes", pt: "vem" },
  { en: "came", pt: "veio" },
  { en: "see", pt: "ver" },
  { en: "saw", pt: "viu" },
  { en: "look", pt: "olhar" },
  { en: "hear", pt: "ouvir" },
  { en: "listen", pt: "escutar" },
  { en: "say", pt: "dizer" },
  { en: "said", pt: "disse" },
  { en: "speak", pt: "falar" },
  { en: "talk", pt: "falar" },
  { en: "know", pt: "saber" },
  { en: "knew", pt: "sabia" },
  { en: "think", pt: "pensar" },
  { en: "thought", pt: "pensou" },
  { en: "want", pt: "querer" },
  { en: "wanted", pt: "queria" },
  { en: "need", pt: "precisar" },
  { en: "like", pt: "gostar" },
  { en: "liked", pt: "gostava" },
  { en: "love", pt: "amar" },
  { en: "loved", pt: "amou" },
  { en: "hate", pt: "odiar" },
  { en: "eat", pt: "comer" },
  { en: "ate", pt: "comeu" },
  { en: "drink", pt: "beber" },
  { en: "drank", pt: "bebeu" },
  { en: "sleep", pt: "dormir" },
  { en: "slept", pt: "dormiu" },
  { en: "work", pt: "trabalhar" },
  { en: "worked", pt: "trabalhou" },
  { en: "play", pt: "jogar" },
  { en: "played", pt: "jogou" },
  { en: "buy", pt: "comprar" },
  { en: "bought", pt: "comprou" },
  { en: "sell", pt: "vender" },
  { en: "give", pt: "dar" },
  { en: "gave", pt: "deu" },
  { en: "take", pt: "tomar" },
  { en: "took", pt: "tomou" },
  { en: "get", pt: "conseguir" },
  { en: "got", pt: "conseguiu" },
  { en: "make", pt: "fazer" },
  { en: "made", pt: "fez" },
  { en: "use", pt: "usar" },
  { en: "used", pt: "usou" },
  { en: "help", pt: "ajudar" },
  { en: "helped", pt: "ajudou" },
  { en: "call", pt: "chamar" },
  { en: "called", pt: "chamou" },
  { en: "try", pt: "tentar" },
  { en: "tried", pt: "tentou" },
  { en: "ask", pt: "perguntar" },
  { en: "asked", pt: "perguntou" },
  { en: "answer", pt: "responder" },
  { en: "answered", pt: "respondeu" },
  { en: "find", pt: "encontrar" },
  { en: "found", pt: "encontrou" },
  { en: "lose", pt: "perder" },
  { en: "lost", pt: "perdeu" },
  { en: "open", pt: "abrir" },
  { en: "close", pt: "fechar" },
  { en: "start", pt: "começar" },
  { en: "stop", pt: "parar" },
  { en: "begin", pt: "começar" },
  { en: "end", pt: "terminar" },
  { en: "finish", pt: "terminar" },
  { en: "live", pt: "viver" },
  { en: "lived", pt: "viveu" },
  { en: "die", pt: "morrer" },
  { en: "died", pt: "morreu" },
  { en: "kill", pt: "matar" },
  { en: "killed", pt: "matou" },
  { en: "run", pt: "correr" },
  { en: "ran", pt: "correu" },
  { en: "walk", pt: "caminhar" },
  { en: "walked", pt: "caminhou" },
  { en: "drive", pt: "dirigir" },
  { en: "drove", pt: "dirigiu" },
  { en: "fly", pt: "voar" },
  { en: "flew", pt: "voou" },
  { en: "read", pt: "ler" },
  { en: "write", pt: "escrever" },
  { en: "wrote", pt: "escreveu" },
  { en: "learn", pt: "aprender" },
  { en: "teach", pt: "ensinar" },
  { en: "understand", pt: "entender" },
  { en: "understood", pt: "entendeu" },
  { en: "remember", pt: "lembrar" },
  { en: "forget", pt: "esquecer" },
  { en: "believe", pt: "acreditar" },
  { en: "feel", pt: "sentir" },
  { en: "felt", pt: "sentiu" },
  { en: "man", pt: "homem" },
  { en: "woman", pt: "mulher" },
  { en: "boy", pt: "menino" },
  { en: "girl", pt: "menina" },
  { en: "child", pt: "criança" },
  { en: "children", pt: "crianças" },
  { en: "baby", pt: "bebê" },
  { en: "father", pt: "pai" },
  { en: "mother", pt: "mãe" },
  { en: "dad", pt: "papai" },
  { en: "mom", pt: "mamãe" },
  { en: "son", pt: "filho" },
  { en: "daughter", pt: "filha" },
  { en: "brother", pt: "irmão" },
  { en: "sister", pt: "irmã" },
  { en: "friend", pt: "amigo" },
  { en: "friends", pt: "amigos" },
  { en: "family", pt: "família" },
  { en: "people", pt: "pessoas" },
  { en: "person", pt: "pessoa" },
  { en: "name", pt: "nome" },
  { en: "house", pt: "casa" },
  { en: "home", pt: "casa" },
  { en: "room", pt: "quarto" },
  { en: "door", pt: "porta" },
  { en: "window", pt: "janela" },
  { en: "school", pt: "escola" },
  { en: "work", pt: "trabalho" },
  { en: "job", pt: "trabalho" },
  { en: "car", pt: "carro" },
  { en: "bus", pt: "ônibus" },
  { en: "train", pt: "trem" },
  { en: "plane", pt: "avião" },
  { en: "boat", pt: "barco" },
  { en: "road", pt: "estrada" },
  { en: "street", pt: "rua" },
  { en: "city", pt: "cidade" },
  { en: "country", pt: "país" },
  { en: "world", pt: "mundo" },
  { en: "water", pt: "água" },
  { en: "fire", pt: "fogo" },
  { en: "air", pt: "ar" },
  { en: "earth", pt: "terra" },
  { en: "sun", pt: "sol" },
  { en: "moon", pt: "lua" },
  { en: "star", pt: "estrela" },
  { en: "sky", pt: "céu" },
  { en: "rain", pt: "chuva" },
  { en: "snow", pt: "neve" },
  { en: "wind", pt: "vento" },
  { en: "tree", pt: "árvore" },
  { en: "flower", pt: "flor" },
  { en: "animal", pt: "animal" },
  { en: "dog", pt: "cachorro" },
  { en: "cat", pt: "gato" },
  { en: "fish", pt: "peixe" },
  { en: "bird", pt: "pássaro" },
  { en: "horse", pt: "cavalo" },
  { en: "food", pt: "comida" },
  { en: "rice", pt: "arroz" },
  { en: "bread", pt: "pão" },
  { en: "meat", pt: "carne" },
  { en: "chicken", pt: "frango" },
  { en: "egg", pt: "ovo" },
  { en: "milk", pt: "leite" },
  { en: "tea", pt: "chá" },
  { en: "coffee", pt: "café" },
  { en: "beer", pt: "cerveja" },
  { en: "wine", pt: "vinho" },
  { en: "money", pt: "dinheiro" },
  { en: "book", pt: "livro" },
  { en: "phone", pt: "telefone" },
  { en: "computer", pt: "computador" },
  { en: "table", pt: "mesa" },
  { en: "chair", pt: "cadeira" },
  { en: "bed", pt: "cama" },
  { en: "time", pt: "tempo" },
  { en: "day", pt: "dia" },
  { en: "night", pt: "noite" },
  { en: "week", pt: "semana" },
  { en: "month", pt: "mês" },
  { en: "year", pt: "ano" },
  { en: "today", pt: "hoje" },
  { en: "tomorrow", pt: "amanhã" },
  { en: "yesterday", pt: "ontem" },
  { en: "morning", pt: "manhã" },
  { en: "afternoon", pt: "tarde" },
  { en: "evening", pt: "tarde" },
  { en: "love", pt: "amor" },
  { en: "life", pt: "vida" },
  { en: "death", pt: "morte" },
  { en: "war", pt: "guerra" },
  { en: "peace", pt: "paz" },
  { en: "god", pt: "deus" },
  { en: "good", pt: "bom" },
  { en: "bad", pt: "mau" },
  { en: "big", pt: "grande" },
  { en: "small", pt: "pequeno" },
  { en: "new", pt: "novo" },
  { en: "old", pt: "velho" },
  { en: "hot", pt: "quente" },
  { en: "cold", pt: "frio" },
  { en: "fast", pt: "rápido" },
  { en: "slow", pt: "lento" },
  { en: "happy", pt: "feliz" },
  { en: "sad", pt: "triste" },
  { en: "angry", pt: "bravo" },
  { en: "tired", pt: "cansado" },
  { en: "sick", pt: "doente" },
  { en: "beautiful", pt: "belo" },
  { en: "ugly", pt: "feio" },
  { en: "rich", pt: "rico" },
  { en: "poor", pt: "pobre" },
  { en: "strong", pt: "forte" },
  { en: "weak", pt: "fraco" },
  { en: "young", pt: "jovem" },
  { en: "easy", pt: "fácil" },
  { en: "hard", pt: "difícil" },
  { en: "right", pt: "certo" },
  { en: "wrong", pt: "errado" },
  { en: "true", pt: "verdadeiro" },
  { en: "false", pt: "falso" },
  { en: "same", pt: "mesmo" },
  { en: "different", pt: "diferente" },
  { en: "many", pt: "muitos" },
  { en: "much", pt: "muito" },
  { en: "more", pt: "mais" },
  { en: "most", pt: "a maioria" },
  { en: "little", pt: "pouco" },
  { en: "few", pt: "poucos" },
  { en: "less", pt: "menos" },
  { en: "all", pt: "tudo" },
  { en: "some", pt: "alguns" },
  { en: "no", pt: "nenhum" },
  { en: "every", pt: "cada" },
  { en: "very", pt: "muito" },
  { en: "too", pt: "também" },
  { en: "also", pt: "também" },
  { en: "and", pt: "e" },
  { en: "or", pt: "ou" },
  { en: "but", pt: "mas" },
  { en: "because", pt: "porque" },
  { en: "so", pt: "então" },
  { en: "if", pt: "se" },
  { en: "then", pt: "então" },
  { en: "now", pt: "agora" },
  { en: "here", pt: "aqui" },
  { en: "there", pt: "lá" },
  { en: "not", pt: "não" },
  { en: "only", pt: "só" },
  { en: "just", pt: "só" },
  { en: "still", pt: "ainda" },
  { en: "again", pt: "de novo" },
  { en: "always", pt: "sempre" },
  { en: "never", pt: "nunca" },
  { en: "sometimes", pt: "às vezes" },
  { en: "maybe", pt: "talvez" },
  { en: "perhaps", pt: "talvez" },
  { en: "one", pt: "um" },
  { en: "two", pt: "dois" },
  { en: "three", pt: "três" },
  { en: "four", pt: "quatro" },
  { en: "five", pt: "cinco" },
  { en: "six", pt: "seis" },
  { en: "seven", pt: "sete" },
  { en: "eight", pt: "oito" },
  { en: "nine", pt: "nove" },
  { en: "ten", pt: "dez" },
  { en: "hundred", pt: "cem" },
  { en: "thousand", pt: "mil" },
  { en: "million", pt: "milhão" },
  { en: "how are you", pt: "como vai" },
  { en: "what is your name", pt: "qual é o seu nome" },
  { en: "my name is", pt: "meu nome é" },
  { en: "i don't know", pt: "não sei" },
  { en: "i don't understand", pt: "não entendo" },
  { en: "i love you", pt: "eu te amo" },
  { en: "i like you", pt: "eu gosto de você" },
  { en: "i miss you", pt: "sinto saudades" },
  { en: "where is the bathroom", pt: "onde fica o banheiro" },
  { en: "how much is it", pt: "quanto custa" },
  { en: "i am hungry", pt: "estou com fome" },
  { en: "i am thirsty", pt: "estou com sede" },
  { en: "i am tired", pt: "estou cansado" },
  { en: "see you later", pt: "até logo" },
  { en: "what time is it", pt: "que horas são" },
  // profanity
  { en: "fuck", pt: "foder" },
  { en: "fucking", pt: "fodido" },
  { en: "shit", pt: "merda" },
  { en: "bitch", pt: "puta" },
  { en: "ass", pt: "cu" },
  { en: "asshole", pt: "idiota" },
  { en: "dick", pt: "pau" },
  { en: "pussy", pt: "buceta" },
  { en: "cock", pt: "pau" },
  { en: "damn", pt: "maldito" },
  { en: "hell", pt: "inferno" },
  { en: "idiot", pt: "idiota" },
  { en: "stupid", pt: "estúpido" },
  { en: "crazy", pt: "louco" },
  { en: "bastard", pt: "bastardo" },
  { en: "motherfucker", pt: "filho da puta" },
  { en: "bullshit", pt: "besteira" },
  { en: "fuck you", pt: "vai se foder" },
  { en: "go to hell", pt: "vai pro inferno" },
  { en: "shut up", pt: "cala a boca" },
];

// ---------- EN <-> RU (Russian) ----------
const DICT_EN_RU = [
  { en: "hello", ru: "привет" },
  { en: "hi", ru: "привет" },
  { en: "good morning", ru: "доброе утро" },
  { en: "good afternoon", ru: "добрый день" },
  { en: "good evening", ru: "добрый вечер" },
  { en: "good night", ru: "спокойной ночи" },
  { en: "goodbye", ru: "до свидания" },
  { en: "bye", ru: "пока" },
  { en: "please", ru: "пожалуйста" },
  { en: "thank you", ru: "спасибо" },
  { en: "thanks", ru: "спасибо" },
  { en: "you're welcome", ru: "пожалуйста" },
  { en: "sorry", ru: "извини" },
  { en: "excuse me", ru: "извините" },
  { en: "yes", ru: "да" },
  { en: "no", ru: "нет" },
  { en: "okay", ru: "ладно" },
  { en: "ok", ru: "ок" },
  { en: "i", ru: "я" },
  { en: "you", ru: "ты" },
  { en: "he", ru: "он" },
  { en: "she", ru: "она" },
  { en: "it", ru: "оно" },
  { en: "we", ru: "мы" },
  { en: "they", ru: "они" },
  { en: "me", ru: "меня" },
  { en: "my", ru: "мой" },
  { en: "your", ru: "твой" },
  { en: "his", ru: "его" },
  { en: "her", ru: "её" },
  { en: "our", ru: "наш" },
  { en: "their", ru: "их" },
  { en: "this", ru: "это" },
  { en: "that", ru: "то" },
  { en: "what", ru: "что" },
  { en: "where", ru: "где" },
  { en: "when", ru: "когда" },
  { en: "why", ru: "почему" },
  { en: "who", ru: "кто" },
  { en: "how", ru: "как" },
  { en: "how much", ru: "сколько" },
  { en: "how many", ru: "сколько" },
  { en: "which", ru: "какой" },
  { en: "is", ru: "есть" },
  { en: "are", ru: "есть" },
  { en: "am", ru: "есть" },
  { en: "was", ru: "был" },
  { en: "were", ru: "были" },
  { en: "be", ru: "быть" },
  { en: "have", ru: "иметь" },
  { en: "has", ru: "имеет" },
  { en: "had", ru: "имел" },
  { en: "do", ru: "делать" },
  { en: "does", ru: "делает" },
  { en: "did", ru: "делал" },
  { en: "go", ru: "идти" },
  { en: "goes", ru: "идёт" },
  { en: "went", ru: "пошёл" },
  { en: "come", ru: "приходить" },
  { en: "comes", ru: "приходит" },
  { en: "came", ru: "пришёл" },
  { en: "see", ru: "видеть" },
  { en: "saw", ru: "видел" },
  { en: "look", ru: "смотреть" },
  { en: "hear", ru: "слышать" },
  { en: "listen", ru: "слушать" },
  { en: "say", ru: "сказать" },
  { en: "said", ru: "сказал" },
  { en: "speak", ru: "говорить" },
  { en: "talk", ru: "разговаривать" },
  { en: "know", ru: "знать" },
  { en: "knew", ru: "знал" },
  { en: "think", ru: "думать" },
  { en: "thought", ru: "думал" },
  { en: "want", ru: "хотеть" },
  { en: "wanted", ru: "хотел" },
  { en: "need", ru: "нужно" },
  { en: "like", ru: "нравиться" },
  { en: "liked", ru: "нравилось" },
  { en: "love", ru: "любить" },
  { en: "loved", ru: "любил" },
  { en: "hate", ru: "ненавидеть" },
  { en: "eat", ru: "есть" },
  { en: "ate", ru: "ел" },
  { en: "drink", ru: "пить" },
  { en: "drank", ru: "пил" },
  { en: "sleep", ru: "спать" },
  { en: "slept", ru: "спал" },
  { en: "work", ru: "работать" },
  { en: "worked", ru: "работал" },
  { en: "play", ru: "играть" },
  { en: "played", ru: "играл" },
  { en: "buy", ru: "купить" },
  { en: "bought", ru: "купил" },
  { en: "sell", ru: "продавать" },
  { en: "give", ru: "дать" },
  { en: "gave", ru: "дал" },
  { en: "take", ru: "взять" },
  { en: "took", ru: "взял" },
  { en: "get", ru: "получить" },
  { en: "got", ru: "получил" },
  { en: "make", ru: "делать" },
  { en: "made", ru: "сделал" },
  { en: "use", ru: "использовать" },
  { en: "used", ru: "использовал" },
  { en: "help", ru: "помочь" },
  { en: "helped", ru: "помог" },
  { en: "call", ru: "звонить" },
  { en: "called", ru: "позвонил" },
  { en: "try", ru: "попробовать" },
  { en: "tried", ru: "пробовал" },
  { en: "ask", ru: "спросить" },
  { en: "asked", ru: "спросил" },
  { en: "answer", ru: "ответить" },
  { en: "answered", ru: "ответил" },
  { en: "find", ru: "найти" },
  { en: "found", ru: "нашёл" },
  { en: "lose", ru: "потерять" },
  { en: "lost", ru: "потерял" },
  { en: "open", ru: "открыть" },
  { en: "close", ru: "закрыть" },
  { en: "start", ru: "начать" },
  { en: "stop", ru: "остановить" },
  { en: "begin", ru: "начать" },
  { en: "end", ru: "конец" },
  { en: "finish", ru: "закончить" },
  { en: "live", ru: "жить" },
  { en: "lived", ru: "жил" },
  { en: "die", ru: "умереть" },
  { en: "died", ru: "умер" },
  { en: "kill", ru: "убить" },
  { en: "killed", ru: "убил" },
  { en: "run", ru: "бежать" },
  { en: "ran", ru: "бежал" },
  { en: "walk", ru: "идти" },
  { en: "walked", ru: "шёл" },
  { en: "drive", ru: "ехать" },
  { en: "drove", ru: "ехал" },
  { en: "fly", ru: "летать" },
  { en: "flew", ru: "летел" },
  { en: "read", ru: "читать" },
  { en: "write", ru: "писать" },
  { en: "wrote", ru: "написал" },
  { en: "learn", ru: "учить" },
  { en: "teach", ru: "учить" },
  { en: "understand", ru: "понимать" },
  { en: "understood", ru: "понял" },
  { en: "remember", ru: "помнить" },
  { en: "forget", ru: "забыть" },
  { en: "believe", ru: "верить" },
  { en: "feel", ru: "чувствовать" },
  { en: "felt", ru: "чувствовал" },
  { en: "man", ru: "мужчина" },
  { en: "woman", ru: "женщина" },
  { en: "boy", ru: "мальчик" },
  { en: "girl", ru: "девочка" },
  { en: "child", ru: "ребёнок" },
  { en: "children", ru: "дети" },
  { en: "baby", ru: "младенец" },
  { en: "father", ru: "отец" },
  { en: "mother", ru: "мать" },
  { en: "dad", ru: "папа" },
  { en: "mom", ru: "мама" },
  { en: "son", ru: "сын" },
  { en: "daughter", ru: "дочь" },
  { en: "brother", ru: "брат" },
  { en: "sister", ru: "сестра" },
  { en: "friend", ru: "друг" },
  { en: "friends", ru: "друзья" },
  { en: "family", ru: "семья" },
  { en: "people", ru: "люди" },
  { en: "person", ru: "человек" },
  { en: "name", ru: "имя" },
  { en: "house", ru: "дом" },
  { en: "home", ru: "дом" },
  { en: "room", ru: "комната" },
  { en: "door", ru: "дверь" },
  { en: "window", ru: "окно" },
  { en: "school", ru: "школа" },
  { en: "work", ru: "работа" },
  { en: "job", ru: "работа" },
  { en: "car", ru: "машина" },
  { en: "bus", ru: "автобус" },
  { en: "train", ru: "поезд" },
  { en: "plane", ru: "самолёт" },
  { en: "boat", ru: "лодка" },
  { en: "road", ru: "дорога" },
  { en: "street", ru: "улица" },
  { en: "city", ru: "город" },
  { en: "country", ru: "страна" },
  { en: "world", ru: "мир" },
  { en: "water", ru: "вода" },
  { en: "fire", ru: "огонь" },
  { en: "air", ru: "воздух" },
  { en: "earth", ru: "земля" },
  { en: "sun", ru: "солнце" },
  { en: "moon", ru: "луна" },
  { en: "star", ru: "звезда" },
  { en: "sky", ru: "небо" },
  { en: "rain", ru: "дождь" },
  { en: "snow", ru: "снег" },
  { en: "wind", ru: "ветер" },
  { en: "tree", ru: "дерево" },
  { en: "flower", ru: "цветок" },
  { en: "animal", ru: "животное" },
  { en: "dog", ru: "собака" },
  { en: "cat", ru: "кошка" },
  { en: "fish", ru: "рыба" },
  { en: "bird", ru: "птица" },
  { en: "horse", ru: "лошадь" },
  { en: "food", ru: "еда" },
  { en: "rice", ru: "рис" },
  { en: "bread", ru: "хлеб" },
  { en: "meat", ru: "мясо" },
  { en: "chicken", ru: "курица" },
  { en: "egg", ru: "яйцо" },
  { en: "milk", ru: "молоко" },
  { en: "tea", ru: "чай" },
  { en: "coffee", ru: "кофе" },
  { en: "beer", ru: "пиво" },
  { en: "wine", ru: "вино" },
  { en: "money", ru: "деньги" },
  { en: "book", ru: "книга" },
  { en: "phone", ru: "телефон" },
  { en: "computer", ru: "компьютер" },
  { en: "table", ru: "стол" },
  { en: "chair", ru: "стул" },
  { en: "bed", ru: "кровать" },
  { en: "time", ru: "время" },
  { en: "day", ru: "день" },
  { en: "night", ru: "ночь" },
  { en: "week", ru: "неделя" },
  { en: "month", ru: "месяц" },
  { en: "year", ru: "год" },
  { en: "today", ru: "сегодня" },
  { en: "tomorrow", ru: "завтра" },
  { en: "yesterday", ru: "вчера" },
  { en: "morning", ru: "утро" },
  { en: "afternoon", ru: "день" },
  { en: "evening", ru: "вечер" },
  { en: "love", ru: "любовь" },
  { en: "life", ru: "жизнь" },
  { en: "death", ru: "смерть" },
  { en: "war", ru: "война" },
  { en: "peace", ru: "мир" },
  { en: "god", ru: "бог" },
  { en: "good", ru: "хороший" },
  { en: "bad", ru: "плохой" },
  { en: "big", ru: "большой" },
  { en: "small", ru: "маленький" },
  { en: "new", ru: "новый" },
  { en: "old", ru: "старый" },
  { en: "hot", ru: "горячий" },
  { en: "cold", ru: "холодный" },
  { en: "fast", ru: "быстрый" },
  { en: "slow", ru: "медленный" },
  { en: "happy", ru: "счастливый" },
  { en: "sad", ru: "грустный" },
  { en: "angry", ru: "злой" },
  { en: "tired", ru: "усталый" },
  { en: "sick", ru: "больной" },
  { en: "beautiful", ru: "красивый" },
  { en: "ugly", ru: "уродливый" },
  { en: "rich", ru: "богатый" },
  { en: "poor", ru: "бедный" },
  { en: "strong", ru: "сильный" },
  { en: "weak", ru: "слабый" },
  { en: "young", ru: "молодой" },
  { en: "easy", ru: "лёгкий" },
  { en: "hard", ru: "трудный" },
  { en: "right", ru: "правильный" },
  { en: "wrong", ru: "неправильный" },
  { en: "true", ru: "правда" },
  { en: "false", ru: "ложь" },
  { en: "same", ru: "тот же" },
  { en: "different", ru: "разный" },
  { en: "many", ru: "много" },
  { en: "much", ru: "много" },
  { en: "more", ru: "больше" },
  { en: "most", ru: "большинство" },
  { en: "little", ru: "мало" },
  { en: "few", ru: "немного" },
  { en: "less", ru: "меньше" },
  { en: "all", ru: "всё" },
  { en: "some", ru: "несколько" },
  { en: "no", ru: "нет" },
  { en: "every", ru: "каждый" },
  { en: "very", ru: "очень" },
  { en: "too", ru: "тоже" },
  { en: "also", ru: "также" },
  { en: "and", ru: "и" },
  { en: "or", ru: "или" },
  { en: "but", ru: "но" },
  { en: "because", ru: "потому что" },
  { en: "so", ru: "поэтому" },
  { en: "if", ru: "если" },
  { en: "then", ru: "тогда" },
  { en: "now", ru: "сейчас" },
  { en: "here", ru: "здесь" },
  { en: "there", ru: "там" },
  { en: "not", ru: "не" },
  { en: "only", ru: "только" },
  { en: "just", ru: "просто" },
  { en: "still", ru: "ещё" },
  { en: "again", ru: "снова" },
  { en: "always", ru: "всегда" },
  { en: "never", ru: "никогда" },
  { en: "sometimes", ru: "иногда" },
  { en: "maybe", ru: "может быть" },
  { en: "perhaps", ru: "возможно" },
  { en: "one", ru: "один" },
  { en: "two", ru: "два" },
  { en: "three", ru: "три" },
  { en: "four", ru: "четыре" },
  { en: "five", ru: "пять" },
  { en: "six", ru: "шесть" },
  { en: "seven", ru: "семь" },
  { en: "eight", ru: "восемь" },
  { en: "nine", ru: "девять" },
  { en: "ten", ru: "десять" },
  { en: "hundred", ru: "сто" },
  { en: "thousand", ru: "тысяча" },
  { en: "million", ru: "миллион" },
  { en: "how are you", ru: "как дела" },
  { en: "what is your name", ru: "как тебя зовут" },
  { en: "my name is", ru: "меня зовут" },
  { en: "i don't know", ru: "я не знаю" },
  { en: "i don't understand", ru: "я не понимаю" },
  { en: "i love you", ru: "я тебя люблю" },
  { en: "i like you", ru: "ты мне нравишься" },
  { en: "i miss you", ru: "я скучаю по тебе" },
  { en: "where is the bathroom", ru: "где туалет" },
  { en: "how much is it", ru: "сколько стоит" },
  { en: "i am hungry", ru: "я голоден" },
  { en: "i am thirsty", ru: "я хочу пить" },
  { en: "i am tired", ru: "я устал" },
  { en: "see you later", ru: "до встречи" },
  { en: "what time is it", ru: "который час" },
  // profanity
  { en: "fuck", ru: "блядь" },
  { en: "fucking", ru: "ёбаный" },
  { en: "shit", ru: "дерьмо" },
  { en: "bitch", ru: "сука" },
  { en: "ass", ru: "задница" },
  { en: "asshole", ru: "мудак" },
  { en: "dick", ru: "хуй" },
  { en: "pussy", ru: "пизда" },
  { en: "cock", ru: "хуй" },
  { en: "damn", ru: "чёрт" },
  { en: "hell", ru: "ад" },
  { en: "idiot", ru: "идиот" },
  { en: "stupid", ru: "глупый" },
  { en: "crazy", ru: "сумасшедший" },
  { en: "bastard", ru: "ублюдок" },
  { en: "motherfucker", ru: "мудак" },
  { en: "bullshit", ru: "хрень" },
  { en: "fuck you", ru: "пошёл на хуй" },
  { en: "go to hell", ru: "иди к чёрту" },
  { en: "shut up", ru: "заткнись" },
];

// ---------- EN <-> UR (Urdu) ----------
const DICT_EN_UR = [
  { en: "hello", ur: "ہیلو" },
  { en: "hi", ur: "ہیلو" },
  { en: "good morning", ur: "صبح بخیر" },
  { en: "good evening", ur: "شام بخیر" },
  { en: "good night", ur: "شب بخیر" },
  { en: "goodbye", ur: "الوداع" },
  { en: "bye", ur: "خدا حافظ" },
  { en: "please", ur: "براہ کرم" },
  { en: "thank you", ur: "شکریہ" },
  { en: "thanks", ur: "شکریہ" },
  { en: "you're welcome", ur: "خیر مقدم" },
  { en: "sorry", ur: "معاف کیجیے" },
  { en: "yes", ur: "ہاں" },
  { en: "no", ur: "نہیں" },
  { en: "okay", ur: "ٹھیک ہے" },
  { en: "ok", ur: "ٹھیک ہے" },
  { en: "i", ur: "میں" },
  { en: "you", ur: "تم" },
  { en: "he", ur: "وہ" },
  { en: "she", ur: "وہ" },
  { en: "we", ur: "ہم" },
  { en: "they", ur: "وہ" },
  { en: "my", ur: "میرا" },
  { en: "your", ur: "تمہارا" },
  { en: "what", ur: "کیا" },
  { en: "where", ur: "کہاں" },
  { en: "when", ur: "کب" },
  { en: "why", ur: "کیوں" },
  { en: "who", ur: "کون" },
  { en: "how", ur: "کیسے" },
  { en: "how much", ur: "کتنا" },
  { en: "is", ur: "ہے" },
  { en: "are", ur: "ہیں" },
  { en: "am", ur: "ہوں" },
  { en: "have", ur: "ہے" },
  { en: "has", ur: "ہے" },
  { en: "do", ur: "کرو" },
  { en: "go", ur: "جاؤ" },
  { en: "come", ur: "آؤ" },
  { en: "see", ur: "دیکھو" },
  { en: "look", ur: "دیکھو" },
  { en: "say", ur: "کہو" },
  { en: "speak", ur: "بولو" },
  { en: "know", ur: "جانو" },
  { en: "think", ur: "سوچو" },
  { en: "want", ur: "چاہو" },
  { en: "need", ur: "ضرورت" },
  { en: "like", ur: "پسند" },
  { en: "love", ur: "محبت" },
  { en: "eat", ur: "کھاؤ" },
  { en: "drink", ur: "پیو" },
  { en: "sleep", ur: "سوو" },
  { en: "work", ur: "کام" },
  { en: "play", ur: "کھیلو" },
  { en: "buy", ur: "خریدو" },
  { en: "give", ur: "دو" },
  { en: "take", ur: "لو" },
  { en: "make", ur: "بناؤ" },
  { en: "help", ur: "مدد" },
  { en: "ask", ur: "پوچھو" },
  { en: "answer", ur: "جواب" },
  { en: "find", ur: "ڈھونڈو" },
  { en: "open", ur: "کھولو" },
  { en: "close", ur: "بند کرو" },
  { en: "man", ur: "آدمی" },
  { en: "woman", ur: "عورت" },
  { en: "boy", ur: "لڑکا" },
  { en: "girl", ur: "لڑکی" },
  { en: "child", ur: "بچہ" },
  { en: "father", ur: "باپ" },
  { en: "mother", ur: "ماں" },
  { en: "son", ur: "بیٹا" },
  { en: "daughter", ur: "بیٹی" },
  { en: "friend", ur: "دوست" },
  { en: "family", ur: "خاندان" },
  { en: "name", ur: "نام" },
  { en: "house", ur: "گھر" },
  { en: "home", ur: "گھر" },
  { en: "water", ur: "پانی" },
  { en: "fire", ur: "آگ" },
  { en: "sun", ur: "سورج" },
  { en: "moon", ur: "چاند" },
  { en: "sky", ur: "آسمان" },
  { en: "rain", ur: "بارش" },
  { en: "food", ur: "کھانا" },
  { en: "bread", ur: "روٹی" },
  { en: "milk", ur: "دودھ" },
  { en: "tea", ur: "چائے" },
  { en: "money", ur: "پیسہ" },
  { en: "book", ur: "کتاب" },
  { en: "car", ur: "گاڑی" },
  { en: "time", ur: "وقت" },
  { en: "day", ur: "دن" },
  { en: "night", ur: "رات" },
  { en: "year", ur: "سال" },
  { en: "today", ur: "آج" },
  { en: "tomorrow", ur: "کل" },
  { en: "yesterday", ur: "کل" },
  { en: "good", ur: "اچھا" },
  { en: "bad", ur: "برا" },
  { en: "big", ur: "بڑا" },
  { en: "small", ur: "چھوٹا" },
  { en: "new", ur: "نیا" },
  { en: "old", ur: "پرانا" },
  { en: "hot", ur: "گرم" },
  { en: "cold", ur: "ٹھنڈا" },
  { en: "fast", ur: "تیز" },
  { en: "happy", ur: "خوش" },
  { en: "sad", ur: "اداس" },
  { en: "angry", ur: "غصہ" },
  { en: "tired", ur: "تھکا" },
  { en: "beautiful", ur: "خوبصورت" },
  { en: "rich", ur: "امیر" },
  { en: "poor", ur: "غریب" },
  { en: "easy", ur: "آسان" },
  { en: "hard", ur: "مشکل" },
  { en: "right", ur: "صحیح" },
  { en: "wrong", ur: "غلط" },
  { en: "true", ur: "سچ" },
  { en: "false", ur: "جھوٹ" },
  { en: "very", ur: "بہت" },
  { en: "and", ur: "اور" },
  { en: "or", ur: "یا" },
  { en: "but", ur: "لیکن" },
  { en: "because", ur: "کیونکہ" },
  { en: "so", ur: "تو" },
  { en: "if", ur: "اگر" },
  { en: "now", ur: "اب" },
  { en: "here", ur: "یہاں" },
  { en: "there", ur: "وہاں" },
  { en: "not", ur: "نہیں" },
  { en: "only", ur: "صرف" },
  { en: "always", ur: "ہمیشہ" },
  { en: "never", ur: "کبھی نہیں" },
  { en: "maybe", ur: "شاید" },
  { en: "one", ur: "ایک" },
  { en: "two", ur: "دو" },
  { en: "three", ur: "تین" },
  { en: "four", ur: "چار" },
  { en: "five", ur: "پانچ" },
  { en: "six", ur: "چھ" },
  { en: "seven", ur: "سات" },
  { en: "eight", ur: "آٹھ" },
  { en: "nine", ur: "نو" },
  { en: "ten", ur: "دس" },
  { en: "how are you", ur: "آپ کیسے ہیں" },
  { en: "what is your name", ur: "آپ کا نام کیا ہے" },
  { en: "my name is", ur: "میرا نام ہے" },
  { en: "i don't know", ur: "مجھے نہیں پتہ" },
  { en: "i love you", ur: "میں تم سے محبت کرتا ہوں" },
  { en: "i am hungry", ur: "مجھے بھوک لگی ہے" },
  { en: "see you later", ur: "بعد میں ملتے ہیں" },
  // profanity
  { en: "fuck", ur: "چود" },
  { en: "shit", ur: "بکواس" },
  { en: "bitch", ur: "رنڈی" },
  { en: "asshole", ur: "گندو" },
  { en: "damn", ur: "لعنت" },
  { en: "idiot", ur: "بیوقوف" },
  { en: "stupid", ur: "بیوقوف" },
  { en: "crazy", ur: "پاگل" },
  { en: "bastard", ur: "حرامی" },
  { en: "bullshit", ur: "بکواس" },
  { en: "fuck you", ur: "چود تمہیں" },
  { en: "shut up", ur: "چپ رہو" },
];
