// =============================================================
//  UNCENSORED TRANSLATOR — DICTIONARY DATA
//  Pivot language: English (en)
//  Each entry: { en: "...", xx: "..." }
//  Phrase keys are matched longest-first by the engine.
//  Nothing is filtered. Profanity/vulgarity is included on purpose
//  so the tool actually translates "any words."
// =============================================================

// ---------- EN <-> ZH (Mandarin, simplified) ----------
const DICT_EN_ZH = [
  // greetings & politeness
  { en: "hello", zh: "你好" },
  { en: "hi", zh: "嗨" },
  { en: "good morning", zh: "早上好" },
  { en: "good afternoon", zh: "下午好" },
  { en: "good evening", zh: "晚上好" },
  { en: "good night", zh: "晚安" },
  { en: "goodbye", zh: "再见" },
  { en: "bye", zh: "再见" },
  { en: "please", zh: "请" },
  { en: "thank you", zh: "谢谢" },
  { en: "thanks", zh: "谢谢" },
  { en: "you're welcome", zh: "不客气" },
  { en: "sorry", zh: "对不起" },
  { en: "excuse me", zh: "打扰一下" },
  { en: "yes", zh: "是" },
  { en: "no", zh: "不" },
  { en: "okay", zh: "好的" },
  { en: "ok", zh: "好的" },
  // pronouns
  { en: "i", zh: "我" },
  { en: "you", zh: "你" },
  { en: "he", zh: "他" },
  { en: "she", zh: "她" },
  { en: "it", zh: "它" },
  { en: "we", zh: "我们" },
  { en: "they", zh: "他们" },
  { en: "me", zh: "我" },
  { en: "my", zh: "我的" },
  { en: "your", zh: "你的" },
  { en: "his", zh: "他的" },
  { en: "her", zh: "她的" },
  { en: "our", zh: "我们的" },
  { en: "their", zh: "他们的" },
  { en: "this", zh: "这个" },
  { en: "that", zh: "那个" },
  // question words
  { en: "what", zh: "什么" },
  { en: "where", zh: "哪里" },
  { en: "when", zh: "什么时候" },
  { en: "why", zh: "为什么" },
  { en: "who", zh: "谁" },
  { en: "how", zh: "怎么" },
  { en: "how much", zh: "多少钱" },
  { en: "how many", zh: "多少" },
  { en: "which", zh: "哪个" },
  // common verbs
  { en: "is", zh: "是" },
  { en: "are", zh: "是" },
  { en: "am", zh: "是" },
  { en: "was", zh: "是" },
  { en: "were", zh: "是" },
  { en: "be", zh: "是" },
  { en: "have", zh: "有" },
  { en: "has", zh: "有" },
  { en: "had", zh: "有" },
  { en: "do", zh: "做" },
  { en: "does", zh: "做" },
  { en: "did", zh: "做" },
  { en: "go", zh: "去" },
  { en: "goes", zh: "去" },
  { en: "went", zh: "去" },
  { en: "come", zh: "来" },
  { en: "comes", zh: "来" },
  { en: "came", zh: "来" },
  { en: "see", zh: "看" },
  { en: "saw", zh: "看" },
  { en: "look", zh: "看" },
  { en: "hear", zh: "听" },
  { en: "listen", zh: "听" },
  { en: "say", zh: "说" },
  { en: "said", zh: "说" },
  { en: "speak", zh: "说" },
  { en: "talk", zh: "说话" },
  { en: "know", zh: "知道" },
  { en: "knew", zh: "知道" },
  { en: "think", zh: "想" },
  { en: "thought", zh: "想" },
  { en: "want", zh: "想要" },
  { en: "wanted", zh: "想要" },
  { en: "need", zh: "需要" },
  { en: "like", zh: "喜欢" },
  { en: "liked", zh: "喜欢" },
  { en: "love", zh: "爱" },
  { en: "loved", zh: "爱" },
  { en: "hate", zh: "恨" },
  { en: "eat", zh: "吃" },
  { en: "ate", zh: "吃" },
  { en: "drink", zh: "喝" },
  { en: "drank", zh: "喝" },
  { en: "sleep", zh: "睡觉" },
  { en: "slept", zh: "睡觉" },
  { en: "work", zh: "工作" },
  { en: "worked", zh: "工作" },
  { en: "play", zh: "玩" },
  { en: "played", zh: "玩" },
  { en: "buy", zh: "买" },
  { en: "bought", zh: "买" },
  { en: "sell", zh: "卖" },
  { en: "give", zh: "给" },
  { en: "gave", zh: "给" },
  { en: "take", zh: "拿" },
  { en: "took", zh: "拿" },
  { en: "get", zh: "得到" },
  { en: "got", zh: "得到" },
  { en: "make", zh: "做" },
  { en: "made", zh: "做" },
  { en: "use", zh: "用" },
  { en: "used", zh: "用" },
  { en: "help", zh: "帮助" },
  { en: "helped", zh: "帮助" },
  { en: "call", zh: "叫" },
  { en: "called", zh: "叫" },
  { en: "try", zh: "试" },
  { en: "tried", zh: "试" },
  { en: "ask", zh: "问" },
  { en: "asked", zh: "问" },
  { en: "answer", zh: "回答" },
  { en: "answered", zh: "回答" },
  { en: "find", zh: "找" },
  { en: "found", zh: "找到" },
  { en: "lose", zh: "丢" },
  { en: "lost", zh: "丢了" },
  { en: "open", zh: "开" },
  { en: "close", zh: "关" },
  { en: "start", zh: "开始" },
  { en: "stop", zh: "停" },
  { en: "begin", zh: "开始" },
  { en: "end", zh: "结束" },
  { en: "finish", zh: "完成" },
  { en: "live", zh: "住" },
  { en: "lived", zh: "住" },
  { en: "die", zh: "死" },
  { en: "died", zh: "死了" },
  { en: "kill", zh: "杀" },
  { en: "killed", zh: "杀了" },
  { en: "run", zh: "跑" },
  { en: "ran", zh: "跑了" },
  { en: "walk", zh: "走" },
  { en: "walked", zh: "走了" },
  { en: "drive", zh: "开车" },
  { en: "drove", zh: "开了车" },
  { en: "fly", zh: "飞" },
  { en: "flew", zh: "飞了" },
  { en: "read", zh: "读" },
  { en: "write", zh: "写" },
  { en: "wrote", zh: "写了" },
  { en: "learn", zh: "学" },
  { en: "teach", zh: "教" },
  { en: "understand", zh: "懂" },
  { en: "understood", zh: "懂了" },
  { en: "remember", zh: "记得" },
  { en: "forget", zh: "忘记" },
  { en: "believe", zh: "相信" },
  { en: "feel", zh: "感觉" },
  { en: "felt", zh: "感觉" },
  // nouns — people
  { en: "man", zh: "男人" },
  { en: "woman", zh: "女人" },
  { en: "boy", zh: "男孩" },
  { en: "girl", zh: "女孩" },
  { en: "child", zh: "孩子" },
  { en: "children", zh: "孩子们" },
  { en: "baby", zh: "婴儿" },
  { en: "father", zh: "爸爸" },
  { en: "mother", zh: "妈妈" },
  { en: "dad", zh: "爸爸" },
  { en: "mom", zh: "妈妈" },
  { en: "son", zh: "儿子" },
  { en: "daughter", zh: "女儿" },
  { en: "brother", zh: "兄弟" },
  { en: "sister", zh: "姐妹" },
  { en: "friend", zh: "朋友" },
  { en: "friends", zh: "朋友们" },
  { en: "family", zh: "家庭" },
  { en: "people", zh: "人" },
  { en: "person", zh: "人" },
  { en: "name", zh: "名字" },
  // nouns — places / things
  { en: "house", zh: "房子" },
  { en: "home", zh: "家" },
  { en: "room", zh: "房间" },
  { en: "door", zh: "门" },
  { en: "window", zh: "窗户" },
  { en: "school", zh: "学校" },
  { en: "work", zh: "工作" },
  { en: "job", zh: "工作" },
  { en: "car", zh: "车" },
  { en: "bus", zh: "公交车" },
  { en: "train", zh: "火车" },
  { en: "plane", zh: "飞机" },
  { en: "boat", zh: "船" },
  { en: "road", zh: "路" },
  { en: "street", zh: "街道" },
  { en: "city", zh: "城市" },
  { en: "country", zh: "国家" },
  { en: "world", zh: "世界" },
  { en: "water", zh: "水" },
  { en: "fire", zh: "火" },
  { en: "air", zh: "空气" },
  { en: "earth", zh: "地球" },
  { en: "sun", zh: "太阳" },
  { en: "moon", zh: "月亮" },
  { en: "star", zh: "星星" },
  { en: "sky", zh: "天空" },
  { en: "rain", zh: "雨" },
  { en: "snow", zh: "雪" },
  { en: "wind", zh: "风" },
  { en: "tree", zh: "树" },
  { en: "flower", zh: "花" },
  { en: "animal", zh: "动物" },
  { en: "dog", zh: "狗" },
  { en: "cat", zh: "猫" },
  { en: "fish", zh: "鱼" },
  { en: "bird", zh: "鸟" },
  { en: "horse", zh: "马" },
  { en: "food", zh: "食物" },
  { en: "rice", zh: "米饭" },
  { en: "bread", zh: "面包" },
  { en: "meat", zh: "肉" },
  { en: "chicken", zh: "鸡肉" },
  { en: "egg", zh: "鸡蛋" },
  { en: "milk", zh: "牛奶" },
  { en: "tea", zh: "茶" },
  { en: "coffee", zh: "咖啡" },
  { en: "beer", zh: "啤酒" },
  { en: "wine", zh: "葡萄酒" },
  { en: "money", zh: "钱" },
  { en: "book", zh: "书" },
  { en: "phone", zh: "电话" },
  { en: "computer", zh: "电脑" },
  { en: "table", zh: "桌子" },
  { en: "chair", zh: "椅子" },
  { en: "bed", zh: "床" },
  { en: "time", zh: "时间" },
  { en: "day", zh: "天" },
  { en: "night", zh: "夜晚" },
  { en: "week", zh: "周" },
  { en: "month", zh: "月" },
  { en: "year", zh: "年" },
  { en: "today", zh: "今天" },
  { en: "tomorrow", zh: "明天" },
  { en: "yesterday", zh: "昨天" },
  { en: "morning", zh: "早上" },
  { en: "afternoon", zh: "下午" },
  { en: "evening", zh: "晚上" },
  { en: "love", zh: "爱" },
  { en: "life", zh: "生活" },
  { en: "death", zh: "死亡" },
  { en: "war", zh: "战争" },
  { en: "peace", zh: "和平" },
  { en: "god", zh: "上帝" },
  // adjectives
  { en: "good", zh: "好" },
  { en: "bad", zh: "坏" },
  { en: "big", zh: "大" },
  { en: "small", zh: "小" },
  { en: "new", zh: "新" },
  { en: "old", zh: "旧" },
  { en: "hot", zh: "热" },
  { en: "cold", zh: "冷" },
  { en: "fast", zh: "快" },
  { en: "slow", zh: "慢" },
  { en: "happy", zh: "快乐" },
  { en: "sad", zh: "伤心" },
  { en: "angry", zh: "生气" },
  { en: "tired", zh: "累" },
  { en: "sick", zh: "病" },
  { en: "beautiful", zh: "漂亮" },
  { en: "ugly", zh: "丑" },
  { en: "rich", zh: "富" },
  { en: "poor", zh: "穷" },
  { en: "strong", zh: "强" },
  { en: "weak", zh: "弱" },
  { en: "young", zh: "年轻" },
  { en: "easy", zh: "容易" },
  { en: "hard", zh: "难" },
  { en: "right", zh: "对" },
  { en: "wrong", zh: "错" },
  { en: "true", zh: "真" },
  { en: "false", zh: "假" },
  { en: "same", zh: "一样" },
  { en: "different", zh: "不同" },
  { en: "many", zh: "多" },
  { en: "much", zh: "多" },
  { en: "more", zh: "更多" },
  { en: "most", zh: "最多" },
  { en: "little", zh: "少" },
  { en: "few", zh: "少" },
  { en: "less", zh: "更少" },
  { en: "all", zh: "所有" },
  { en: "some", zh: "一些" },
  { en: "no", zh: "没有" },
  { en: "every", zh: "每" },
  // adverbs / connectors
  { en: "very", zh: "很" },
  { en: "too", zh: "也" },
  { en: "also", zh: "也" },
  { en: "and", zh: "和" },
  { en: "or", zh: "或" },
  { en: "but", zh: "但是" },
  { en: "because", zh: "因为" },
  { en: "so", zh: "所以" },
  { en: "if", zh: "如果" },
  { en: "then", zh: "然后" },
  { en: "now", zh: "现在" },
  { en: "here", zh: "这里" },
  { en: "there", zh: "那里" },
  { en: "not", zh: "不" },
  { en: "only", zh: "只" },
  { en: "just", zh: "就" },
  { en: "still", zh: "还" },
  { en: "again", zh: "再" },
  { en: "always", zh: "总是" },
  { en: "never", zh: "从不" },
  { en: "sometimes", zh: "有时" },
  { en: "maybe", zh: "也许" },
  { en: "perhaps", zh: "也许" },
  // numbers
  { en: "one", zh: "一" },
  { en: "two", zh: "二" },
  { en: "three", zh: "三" },
  { en: "four", zh: "四" },
  { en: "five", zh: "五" },
  { en: "six", zh: "六" },
  { en: "seven", zh: "七" },
  { en: "eight", zh: "八" },
  { en: "nine", zh: "九" },
  { en: "ten", zh: "十" },
  { en: "hundred", zh: "百" },
  { en: "thousand", zh: "千" },
  { en: "million", zh: "百万" },
  // question / misc phrases
  { en: "how are you", zh: "你好吗" },
  { en: "what is your name", zh: "你叫什么名字" },
  { en: "my name is", zh: "我的名字是" },
  { en: "i don't know", zh: "我不知道" },
  { en: "i don't understand", zh: "我不懂" },
  { en: "i love you", zh: "我爱你" },
  { en: "i like you", zh: "我喜欢你" },
  { en: "i miss you", zh: "我想你" },
  { en: "where is the bathroom", zh: "洗手间在哪里" },
  { en: "how much is it", zh: "多少钱" },
  { en: "i am hungry", zh: "我饿了" },
  { en: "i am thirsty", zh: "我渴了" },
  { en: "i am tired", zh: "我累了" },
  { en: "see you later", zh: "回头见" },
  { en: "what time is it", zh: "现在几点" },
  // profanity / vulgarity (uncensored on purpose)
  { en: "fuck", zh: "操" },
  { en: "fucking", zh: "他妈的" },
  { en: "shit", zh: "狗屎" },
  { en: "bitch", zh: "婊子" },
  { en: "ass", zh: "屁股" },
  { en: "asshole", zh: "混蛋" },
  { en: "dick", zh: "鸡巴" },
  { en: "pussy", zh: "逼" },
  { en: "cock", zh: "鸡巴" },
  { en: "damn", zh: "该死" },
  { en: "hell", zh: "地狱" },
  { en: "idiot", zh: "白痴" },
  { en: "stupid", zh: "笨" },
  { en: "crazy", zh: "疯" },
  { en: "bastard", zh: "杂种" },
  { en: "motherfucker", zh: "他妈的混蛋" },
  { en: "bullshit", zh: "胡说八道" },
  { en: "fuck you", zh: "操你" },
  { en: "go to hell", zh: "去死吧" },
  { en: "shut up", zh: "闭嘴" },
];

// ---------- EN <-> HI (Hindi, devanagari) ----------
const DICT_EN_HI = [
  { en: "hello", hi: "नमस्ते" },
  { en: "hi", hi: "नमस्ते" },
  { en: "good morning", hi: "सुप्रभात" },
  { en: "good evening", hi: "शुभ संध्या" },
  { en: "good night", hi: "शुभ रात्रि" },
  { en: "goodbye", hi: "अलविदा" },
  { en: "bye", hi: "अलविदा" },
  { en: "please", hi: "कृपया" },
  { en: "thank you", hi: "धन्यवाद" },
  { en: "thanks", hi: "धन्यवाद" },
  { en: "sorry", hi: "माफ़ कीजिए" },
  { en: "yes", hi: "हाँ" },
  { en: "no", hi: "नहीं" },
  { en: "okay", hi: "ठीक है" },
  { en: "ok", hi: "ठीक है" },
  { en: "i", hi: "मैं" },
  { en: "you", hi: "तुम" },
  { en: "he", hi: "वह" },
  { en: "she", hi: "वह" },
  { en: "we", hi: "हम" },
  { en: "they", hi: "वे" },
  { en: "me", hi: "मुझे" },
  { en: "my", hi: "मेरा" },
  { en: "your", hi: "तुम्हारा" },
  { en: "what", hi: "क्या" },
  { en: "where", hi: "कहाँ" },
  { en: "when", hi: "कब" },
  { en: "why", hi: "क्यों" },
  { en: "who", hi: "कौन" },
  { en: "how", hi: "कैसे" },
  { en: "is", hi: "है" },
  { en: "are", hi: "हैं" },
  { en: "am", hi: "हूँ" },
  { en: "have", hi: "है" },
  { en: "has", hi: "है" },
  { en: "do", hi: "करो" },
  { en: "go", hi: "जाओ" },
  { en: "come", hi: "आओ" },
  { en: "see", hi: "देखो" },
  { en: "look", hi: "देखो" },
  { en: "say", hi: "कहो" },
  { en: "speak", hi: "बोलो" },
  { en: "know", hi: "जानो" },
  { en: "think", hi: "सोचो" },
  { en: "want", hi: "चाहो" },
  { en: "need", hi: "ज़रूरत" },
  { en: "like", hi: "पसंद" },
  { en: "love", hi: "प्यार" },
  { en: "eat", hi: "खाओ" },
  { en: "drink", hi: "पियो" },
  { en: "sleep", hi: "सोओ" },
  { en: "work", hi: "काम" },
  { en: "play", hi: "खेलो" },
  { en: "buy", hi: "खरीदो" },
  { en: "give", hi: "दो" },
  { en: "take", hi: "लो" },
  { en: "make", hi: "बनाओ" },
  { en: "help", hi: "मदद" },
  { en: "ask", hi: "पूछो" },
  { en: "answer", hi: "जवाब" },
  { en: "find", hi: "ढूँढो" },
  { en: "open", hi: "खोलो" },
  { en: "close", hi: "बंद करो" },
  { en: "man", hi: "आदमी" },
  { en: "woman", hi: "औरत" },
  { en: "boy", hi: "लड़का" },
  { en: "girl", hi: "लड़की" },
  { en: "child", hi: "बच्चा" },
  { en: "father", hi: "पिता" },
  { en: "mother", hi: "माता" },
  { en: "son", hi: "बेटा" },
  { en: "daughter", hi: "बेटी" },
  { en: "friend", hi: "दोस्त" },
  { en: "family", hi: "परिवार" },
  { en: "people", hi: "लोग" },
  { en: "name", hi: "नाम" },
  { en: "house", hi: "घर" },
  { en: "home", hi: "घर" },
  { en: "water", hi: "पानी" },
  { en: "fire", hi: "आग" },
  { en: "sun", hi: "सूरज" },
  { en: "moon", hi: "चाँद" },
  { en: "sky", hi: "आसमान" },
  { en: "rain", hi: "बारिश" },
  { en: "food", hi: "खाना" },
  { en: "rice", hi: "चावल" },
  { en: "bread", hi: "रोटी" },
  { en: "milk", hi: "दूध" },
  { en: "tea", hi: "चाय" },
  { en: "coffee", hi: "कॉफी" },
  { en: "money", hi: "पैसा" },
  { en: "book", hi: "किताब" },
  { en: "phone", hi: "फ़ोन" },
  { en: "car", hi: "गाड़ी" },
  { en: "time", hi: "समय" },
  { en: "day", hi: "दिन" },
  { en: "night", hi: "रात" },
  { en: "year", hi: "साल" },
  { en: "today", hi: "आज" },
  { en: "tomorrow", hi: "कल" },
  { en: "yesterday", hi: "कल" },
  { en: "good", hi: "अच्छा" },
  { en: "bad", hi: "बुरा" },
  { en: "big", hi: "बड़ा" },
  { en: "small", hi: "छोटा" },
  { en: "new", hi: "नया" },
  { en: "old", hi: "पुराना" },
  { en: "hot", hi: "गरम" },
  { en: "cold", hi: "ठंडा" },
  { en: "fast", hi: "तेज़" },
  { en: "happy", hi: "खुश" },
  { en: "sad", hi: "दुखी" },
  { en: "angry", hi: "गुस्सा" },
  { en: "tired", hi: "थका" },
  { en: "beautiful", hi: "सुंदर" },
  { en: "rich", hi: "अमीर" },
  { en: "poor", hi: "गरीब" },
  { en: "strong", hi: "मज़बूत" },
  { en: "easy", hi: "आसान" },
  { en: "hard", hi: "मुश्किल" },
  { en: "right", hi: "सही" },
  { en: "wrong", hi: "गलत" },
  { en: "true", hi: "सच" },
  { en: "false", hi: "झूठ" },
  { en: "many", hi: "बहुत" },
  { en: "more", hi: "और" },
  { en: "all", hi: "सब" },
  { en: "some", hi: "कुछ" },
  { en: "very", hi: "बहुत" },
  { en: "and", hi: "और" },
  { en: "or", hi: "या" },
  { en: "but", hi: "लेकिन" },
  { en: "because", hi: "क्योंकि" },
  { en: "so", hi: "तो" },
  { en: "if", hi: "अगर" },
  { en: "now", hi: "अभी" },
  { en: "here", hi: "यहाँ" },
  { en: "there", hi: "वहाँ" },
  { en: "not", hi: "नहीं" },
  { en: "only", hi: "सिर्फ़" },
  { en: "again", hi: "फिर" },
  { en: "always", hi: "हमेशा" },
  { en: "never", hi: "कभी नहीं" },
  { en: "maybe", hi: "शायद" },
  { en: "one", hi: "एक" },
  { en: "two", hi: "दो" },
  { en: "three", hi: "तीन" },
  { en: "four", hi: "चार" },
  { en: "five", hi: "पाँच" },
  { en: "six", hi: "छह" },
  { en: "seven", hi: "सात" },
  { en: "eight", hi: "आठ" },
  { en: "nine", hi: "नौ" },
  { en: "ten", hi: "दस" },
  { en: "how are you", hi: "आप कैसे हैं" },
  { en: "what is your name", hi: "आपका नाम क्या है" },
  { en: "my name is", hi: "मेरा नाम है" },
  { en: "i don't know", hi: "मुझे नहीं पता" },
  { en: "i love you", hi: "मैं तुमसे प्यार करता हूँ" },
  { en: "i like you", hi: "मुझे तुम पसंद हो" },
  { en: "i am hungry", hi: "मुझे भूख लगी है" },
  { en: "i am tired", hi: "मैं थक गया हूँ" },
  { en: "see you later", hi: "बाद में मिलते हैं" },
  // profanity
  { en: "fuck", hi: "चोद" },
  { en: "fucking", hi: "चुदाई" },
  { en: "shit", hi: "बकवास" },
  { en: "bitch", hi: "रंडी" },
  { en: "asshole", hi: "गांडू" },
  { en: "dick", hi: "लंड" },
  { en: "pussy", hi: "चूत" },
  { en: "damn", hi: "ख़राब" },
  { en: "idiot", hi: "बेवकूफ़" },
  { en: "stupid", hi: "बेवकूफ़" },
  { en: "crazy", hi: "पागल" },
  { en: "bastard", hi: "हरामी" },
  { en: "bullshit", hi: "बकवास" },
  { en: "fuck you", hi: "चोद तुझे" },
  { en: "shut up", hi: "चुप करो" },
];

// ---------- EN <-> ES (Spanish) ----------
const DICT_EN_ES = [
  { en: "hello", es: "hola" },
  { en: "hi", es: "hola" },
  { en: "good morning", es: "buenos días" },
  { en: "good afternoon", es: "buenas tardes" },
  { en: "good evening", es: "buenas noches" },
  { en: "good night", es: "buenas noches" },
  { en: "goodbye", es: "adiós" },
  { en: "bye", es: "adiós" },
  { en: "please", es: "por favor" },
  { en: "thank you", es: "gracias" },
  { en: "thanks", es: "gracias" },
  { en: "you're welcome", es: "de nada" },
  { en: "sorry", es: "lo siento" },
  { en: "excuse me", es: "disculpe" },
  { en: "yes", es: "sí" },
  { en: "no", es: "no" },
  { en: "okay", es: "vale" },
  { en: "ok", es: "vale" },
  { en: "i", es: "yo" },
  { en: "you", es: "tú" },
  { en: "he", es: "él" },
  { en: "she", es: "ella" },
  { en: "it", es: "eso" },
  { en: "we", es: "nosotros" },
  { en: "they", es: "ellos" },
  { en: "me", es: "me" },
  { en: "my", es: "mi" },
  { en: "your", es: "tu" },
  { en: "his", es: "su" },
  { en: "her", es: "su" },
  { en: "our", es: "nuestro" },
  { en: "their", es: "su" },
  { en: "this", es: "esto" },
  { en: "that", es: "eso" },
  { en: "what", es: "qué" },
  { en: "where", es: "dónde" },
  { en: "when", es: "cuándo" },
  { en: "why", es: "por qué" },
  { en: "who", es: "quién" },
  { en: "how", es: "cómo" },
  { en: "how much", es: "cuánto" },
  { en: "how many", es: "cuántos" },
  { en: "which", es: "cuál" },
  { en: "is", es: "es" },
  { en: "are", es: "son" },
  { en: "am", es: "soy" },
  { en: "was", es: "era" },
  { en: "were", es: "eran" },
  { en: "be", es: "ser" },
  { en: "have", es: "tener" },
  { en: "has", es: "tiene" },
  { en: "had", es: "tenía" },
  { en: "do", es: "hacer" },
  { en: "does", es: "hace" },
  { en: "did", es: "hizo" },
  { en: "go", es: "ir" },
  { en: "goes", es: "va" },
  { en: "went", es: "fue" },
  { en: "come", es: "venir" },
  { en: "comes", es: "viene" },
  { en: "came", es: "vino" },
  { en: "see", es: "ver" },
  { en: "saw", es: "vio" },
  { en: "look", es: "mirar" },
  { en: "hear", es: "oír" },
  { en: "listen", es: "escuchar" },
  { en: "say", es: "decir" },
  { en: "said", es: "dijo" },
  { en: "speak", es: "hablar" },
  { en: "talk", es: "hablar" },
  { en: "know", es: "saber" },
  { en: "knew", es: "sabía" },
  { en: "think", es: "pensar" },
  { en: "thought", es: "pensó" },
  { en: "want", es: "querer" },
  { en: "wanted", es: "quería" },
  { en: "need", es: "necesitar" },
  { en: "like", es: "gustar" },
  { en: "liked", es: "gustaba" },
  { en: "love", es: "amar" },
  { en: "loved", es: "amó" },
  { en: "hate", es: "odiar" },
  { en: "eat", es: "comer" },
  { en: "ate", es: "comió" },
  { en: "drink", es: "beber" },
  { en: "drank", es: "bebió" },
  { en: "sleep", es: "dormir" },
  { en: "slept", es: "durmió" },
  { en: "work", es: "trabajar" },
  { en: "worked", es: "trabajó" },
  { en: "play", es: "jugar" },
  { en: "played", es: "jugó" },
  { en: "buy", es: "comprar" },
  { en: "bought", es: "compró" },
  { en: "sell", es: "vender" },
  { en: "give", es: "dar" },
  { en: "gave", es: "dio" },
  { en: "take", es: "tomar" },
  { en: "took", es: "tomó" },
  { en: "get", es: "conseguir" },
  { en: "got", es: "consiguió" },
  { en: "make", es: "hacer" },
  { en: "made", es: "hizo" },
  { en: "use", es: "usar" },
  { en: "used", es: "usó" },
  { en: "help", es: "ayudar" },
  { en: "helped", es: "ayudó" },
  { en: "call", es: "llamar" },
  { en: "called", es: "llamó" },
  { en: "try", es: "intentar" },
  { en: "tried", es: "intentó" },
  { en: "ask", es: "preguntar" },
  { en: "asked", es: "preguntó" },
  { en: "answer", es: "responder" },
  { en: "answered", es: "respondió" },
  { en: "find", es: "encontrar" },
  { en: "found", es: "encontró" },
  { en: "lose", es: "perder" },
  { en: "lost", es: "perdió" },
  { en: "open", es: "abrir" },
  { en: "close", es: "cerrar" },
  { en: "start", es: "empezar" },
  { en: "stop", es: "parar" },
  { en: "begin", es: "empezar" },
  { en: "end", es: "terminar" },
  { en: "finish", es: "terminar" },
  { en: "live", es: "vivir" },
  { en: "lived", es: "vivió" },
  { en: "die", es: "morir" },
  { en: "died", es: "murió" },
  { en: "kill", es: "matar" },
  { en: "killed", es: "mató" },
  { en: "run", es: "correr" },
  { en: "ran", es: "corrió" },
  { en: "walk", es: "caminar" },
  { en: "walked", es: "caminó" },
  { en: "drive", es: "conducir" },
  { en: "drove", es: "condujo" },
  { en: "fly", es: "volar" },
  { en: "flew", es: "voló" },
  { en: "read", es: "leer" },
  { en: "write", es: "escribir" },
  { en: "wrote", es: "escribió" },
  { en: "learn", es: "aprender" },
  { en: "teach", es: "enseñar" },
  { en: "understand", es: "entender" },
  { en: "understood", es: "entendió" },
  { en: "remember", es: "recordar" },
  { en: "forget", es: "olvidar" },
  { en: "believe", es: "creer" },
  { en: "feel", es: "sentir" },
  { en: "felt", es: "sintió" },
  { en: "man", es: "hombre" },
  { en: "woman", es: "mujer" },
  { en: "boy", es: "niño" },
  { en: "girl", es: "niña" },
  { en: "child", es: "niño" },
  { en: "children", es: "niños" },
  { en: "baby", es: "bebé" },
  { en: "father", es: "padre" },
  { en: "mother", es: "madre" },
  { en: "dad", es: "papá" },
  { en: "mom", es: "mamá" },
  { en: "son", es: "hijo" },
  { en: "daughter", es: "hija" },
  { en: "brother", es: "hermano" },
  { en: "sister", es: "hermana" },
  { en: "friend", es: "amigo" },
  { en: "friends", es: "amigos" },
  { en: "family", es: "familia" },
  { en: "people", es: "gente" },
  { en: "person", es: "persona" },
  { en: "name", es: "nombre" },
  { en: "house", es: "casa" },
  { en: "home", es: "casa" },
  { en: "room", es: "habitación" },
  { en: "door", es: "puerta" },
  { en: "window", es: "ventana" },
  { en: "school", es: "escuela" },
  { en: "work", es: "trabajo" },
  { en: "job", es: "trabajo" },
  { en: "car", es: "coche" },
  { en: "bus", es: "autobús" },
  { en: "train", es: "tren" },
  { en: "plane", es: "avión" },
  { en: "boat", es: "barco" },
  { en: "road", es: "camino" },
  { en: "street", es: "calle" },
  { en: "city", es: "ciudad" },
  { en: "country", es: "país" },
  { en: "world", es: "mundo" },
  { en: "water", es: "agua" },
  { en: "fire", es: "fuego" },
  { en: "air", es: "aire" },
  { en: "earth", es: "tierra" },
  { en: "sun", es: "sol" },
  { en: "moon", es: "luna" },
  { en: "star", es: "estrella" },
  { en: "sky", es: "cielo" },
  { en: "rain", es: "lluvia" },
  { en: "snow", es: "nieve" },
  { en: "wind", es: "viento" },
  { en: "tree", es: "árbol" },
  { en: "flower", es: "flor" },
  { en: "animal", es: "animal" },
  { en: "dog", es: "perro" },
  { en: "cat", es: "gato" },
  { en: "fish", es: "pez" },
  { en: "bird", es: "pájaro" },
  { en: "horse", es: "caballo" },
  { en: "food", es: "comida" },
  { en: "rice", es: "arroz" },
  { en: "bread", es: "pan" },
  { en: "meat", es: "carne" },
  { en: "chicken", es: "pollo" },
  { en: "egg", es: "huevo" },
  { en: "milk", es: "leche" },
  { en: "tea", es: "té" },
  { en: "coffee", es: "café" },
  { en: "beer", es: "cerveza" },
  { en: "wine", es: "vino" },
  { en: "money", es: "dinero" },
  { en: "book", es: "libro" },
  { en: "phone", es: "teléfono" },
  { en: "computer", es: "ordenador" },
  { en: "table", es: "mesa" },
  { en: "chair", es: "silla" },
  { en: "bed", es: "cama" },
  { en: "time", es: "tiempo" },
  { en: "day", es: "día" },
  { en: "night", es: "noche" },
  { en: "week", es: "semana" },
  { en: "month", es: "mes" },
  { en: "year", es: "año" },
  { en: "today", es: "hoy" },
  { en: "tomorrow", es: "mañana" },
  { en: "yesterday", es: "ayer" },
  { en: "morning", es: "mañana" },
  { en: "afternoon", es: "tarde" },
  { en: "evening", es: "tarde" },
  { en: "love", es: "amor" },
  { en: "life", es: "vida" },
  { en: "death", es: "muerte" },
  { en: "war", es: "guerra" },
  { en: "peace", es: "paz" },
  { en: "god", es: "dios" },
  { en: "good", es: "bueno" },
  { en: "bad", es: "malo" },
  { en: "big", es: "grande" },
  { en: "small", es: "pequeño" },
  { en: "new", es: "nuevo" },
  { en: "old", es: "viejo" },
  { en: "hot", es: "caliente" },
  { en: "cold", es: "frío" },
  { en: "fast", es: "rápido" },
  { en: "slow", es: "lento" },
  { en: "happy", es: "feliz" },
  { en: "sad", es: "triste" },
  { en: "angry", es: "enfadado" },
  { en: "tired", es: "cansado" },
  { en: "sick", es: "enfermo" },
  { en: "beautiful", es: "hermoso" },
  { en: "ugly", es: "feo" },
  { en: "rich", es: "rico" },
  { en: "poor", es: "pobre" },
  { en: "strong", es: "fuerte" },
  { en: "weak", es: "débil" },
  { en: "young", es: "joven" },
  { en: "easy", es: "fácil" },
  { en: "hard", es: "difícil" },
  { en: "right", es: "correcto" },
  { en: "wrong", es: "equivocado" },
  { en: "true", es: "verdadero" },
  { en: "false", es: "falso" },
  { en: "same", es: "mismo" },
  { en: "different", es: "diferente" },
  { en: "many", es: "muchos" },
  { en: "much", es: "mucho" },
  { en: "more", es: "más" },
  { en: "most", es: "la mayoría" },
  { en: "little", es: "poco" },
  { en: "few", es: "pocos" },
  { en: "less", es: "menos" },
  { en: "all", es: "todo" },
  { en: "some", es: "algunos" },
  { en: "no", es: "ninguno" },
  { en: "every", es: "cada" },
  { en: "very", es: "muy" },
  { en: "too", es: "también" },
  { en: "also", es: "también" },
  { en: "and", es: "y" },
  { en: "or", es: "o" },
  { en: "but", es: "pero" },
  { en: "because", es: "porque" },
  { en: "so", es: "así que" },
  { en: "if", es: "si" },
  { en: "then", es: "entonces" },
  { en: "now", es: "ahora" },
  { en: "here", es: "aquí" },
  { en: "there", es: "allí" },
  { en: "not", es: "no" },
  { en: "only", es: "solo" },
  { en: "just", es: "solo" },
  { en: "still", es: "todavía" },
  { en: "again", es: "otra vez" },
  { en: "always", es: "siempre" },
  { en: "never", es: "nunca" },
  { en: "sometimes", es: "a veces" },
  { en: "maybe", es: "quizás" },
  { en: "perhaps", es: "tal vez" },
  { en: "one", es: "uno" },
  { en: "two", es: "dos" },
  { en: "three", es: "tres" },
  { en: "four", es: "cuatro" },
  { en: "five", es: "cinco" },
  { en: "six", es: "seis" },
  { en: "seven", es: "siete" },
  { en: "eight", es: "ocho" },
  { en: "nine", es: "nueve" },
  { en: "ten", es: "diez" },
  { en: "hundred", es: "cien" },
  { en: "thousand", es: "mil" },
  { en: "million", es: "millón" },
  { en: "how are you", es: "cómo estás" },
  { en: "what is your name", es: "cuál es tu nombre" },
  { en: "my name is", es: "mi nombre es" },
  { en: "i don't know", es: "no sé" },
  { en: "i don't understand", es: "no entiendo" },
  { en: "i love you", es: "te amo" },
  { en: "i like you", es: "me gustas" },
  { en: "i miss you", es: "te extraño" },
  { en: "where is the bathroom", es: "dónde está el baño" },
  { en: "how much is it", es: "cuánto cuesta" },
  { en: "i am hungry", es: "tengo hambre" },
  { en: "i am thirsty", es: "tengo sed" },
  { en: "i am tired", es: "estoy cansado" },
  { en: "see you later", es: "hasta luego" },
  { en: "what time is it", es: "qué hora es" },
  // profanity
  { en: "fuck", es: "joder" },
  { en: "fucking", es: "jodido" },
  { en: "shit", es: "mierda" },
  { en: "bitch", es: "puta" },
  { en: "ass", es: "culo" },
  { en: "asshole", es: "cabrón" },
  { en: "dick", es: "pene" },
  { en: "pussy", es: "coño" },
  { en: "cock", es: "verga" },
  { en: "damn", es: "maldito" },
  { en: "hell", es: "infierno" },
  { en: "idiot", es: "idiota" },
  { en: "stupid", es: "estúpido" },
  { en: "crazy", es: "loco" },
  { en: "bastard", es: "bastardo" },
  { en: "motherfucker", es: "hijo de puta" },
  { en: "bullshit", es: "tonterías" },
  { en: "fuck you", es: "vete a la mierda" },
  { en: "go to hell", es: "vete al infierno" },
  { en: "shut up", es: "cállate" },
];

// ---------- EN <-> FR (French) ----------
const DICT_EN_FR = [
  { en: "hello", fr: "bonjour" },
  { en: "hi", fr: "salut" },
  { en: "good morning", fr: "bonjour" },
  { en: "good afternoon", fr: "bon après-midi" },
  { en: "good evening", fr: "bonsoir" },
  { en: "good night", fr: "bonne nuit" },
  { en: "goodbye", fr: "au revoir" },
  { en: "bye", fr: "au revoir" },
  { en: "please", fr: "s'il vous plaît" },
  { en: "thank you", fr: "merci" },
  { en: "thanks", fr: "merci" },
  { en: "you're welcome", fr: "de rien" },
  { en: "sorry", fr: "pardon" },
  { en: "excuse me", fr: "excusez-moi" },
  { en: "yes", fr: "oui" },
  { en: "no", fr: "non" },
  { en: "okay", fr: "d'accord" },
  { en: "ok", fr: "d'accord" },
  { en: "i", fr: "je" },
  { en: "you", fr: "tu" },
  { en: "he", fr: "il" },
  { en: "she", fr: "elle" },
  { en: "it", fr: "il" },
  { en: "we", fr: "nous" },
  { en: "they", fr: "ils" },
  { en: "me", fr: "me" },
  { en: "my", fr: "mon" },
  { en: "your", fr: "ton" },
  { en: "his", fr: "son" },
  { en: "her", fr: "son" },
  { en: "our", fr: "notre" },
  { en: "their", fr: "leur" },
  { en: "this", fr: "ceci" },
  { en: "that", fr: "cela" },
  { en: "what", fr: "quoi" },
  { en: "where", fr: "où" },
  { en: "when", fr: "quand" },
  { en: "why", fr: "pourquoi" },
  { en: "who", fr: "qui" },
  { en: "how", fr: "comment" },
  { en: "how much", fr: "combien" },
  { en: "how many", fr: "combien" },
  { en: "which", fr: "quel" },
  { en: "is", fr: "est" },
  { en: "are", fr: "sont" },
  { en: "am", fr: "suis" },
  { en: "was", fr: "était" },
  { en: "were", fr: "étaient" },
  { en: "be", fr: "être" },
  { en: "have", fr: "avoir" },
  { en: "has", fr: "a" },
  { en: "had", fr: "avait" },
  { en: "do", fr: "faire" },
  { en: "does", fr: "fait" },
  { en: "did", fr: "a fait" },
  { en: "go", fr: "aller" },
  { en: "goes", fr: "va" },
  { en: "went", fr: "est allé" },
  { en: "come", fr: "venir" },
  { en: "comes", fr: "vient" },
  { en: "came", fr: "est venu" },
  { en: "see", fr: "voir" },
  { en: "saw", fr: "a vu" },
  { en: "look", fr: "regarder" },
  { en: "hear", fr: "entendre" },
  { en: "listen", fr: "écouter" },
  { en: "say", fr: "dire" },
  { en: "said", fr: "a dit" },
  { en: "speak", fr: "parler" },
  { en: "talk", fr: "parler" },
  { en: "know", fr: "savoir" },
  { en: "knew", fr: "savait" },
  { en: "think", fr: "penser" },
  { en: "thought", fr: "a pensé" },
  { en: "want", fr: "vouloir" },
  { en: "wanted", fr: "voulait" },
  { en: "need", fr: "avoir besoin" },
  { en: "like", fr: "aimer" },
  { en: "liked", fr: "aimait" },
  { en: "love", fr: "aimer" },
  { en: "loved", fr: "aimait" },
  { en: "hate", fr: "détester" },
  { en: "eat", fr: "manger" },
  { en: "ate", fr: "a mangé" },
  { en: "drink", fr: "boire" },
  { en: "drank", fr: "a bu" },
  { en: "sleep", fr: "dormir" },
  { en: "slept", fr: "a dormi" },
  { en: "work", fr: "travailler" },
  { en: "worked", fr: "a travaillé" },
  { en: "play", fr: "jouer" },
  { en: "played", fr: "a joué" },
  { en: "buy", fr: "acheter" },
  { en: "bought", fr: "a acheté" },
  { en: "sell", fr: "vendre" },
  { en: "give", fr: "donner" },
  { en: "gave", fr: "a donné" },
  { en: "take", fr: "prendre" },
  { en: "took", fr: "a pris" },
  { en: "get", fr: "obtenir" },
  { en: "got", fr: "a obtenu" },
  { en: "make", fr: "faire" },
  { en: "made", fr: "a fait" },
  { en: "use", fr: "utiliser" },
  { en: "used", fr: "a utilisé" },
  { en: "help", fr: "aider" },
  { en: "helped", fr: "a aidé" },
  { en: "call", fr: "appeler" },
  { en: "called", fr: "a appelé" },
  { en: "try", fr: "essayer" },
  { en: "tried", fr: "a essayé" },
  { en: "ask", fr: "demander" },
  { en: "asked", fr: "a demandé" },
  { en: "answer", fr: "répondre" },
  { en: "answered", fr: "a répondu" },
  { en: "find", fr: "trouver" },
  { en: "found", fr: "a trouvé" },
  { en: "lose", fr: "perdre" },
  { en: "lost", fr: "a perdu" },
  { en: "open", fr: "ouvrir" },
  { en: "close", fr: "fermer" },
  { en: "start", fr: "commencer" },
  { en: "stop", fr: "arrêter" },
  { en: "begin", fr: "commencer" },
  { en: "end", fr: "finir" },
  { en: "finish", fr: "finir" },
  { en: "live", fr: "vivre" },
  { en: "lived", fr: "a vécu" },
  { en: "die", fr: "mourir" },
  { en: "died", fr: "est mort" },
  { en: "kill", fr: "tuer" },
  { en: "killed", fr: "a tué" },
  { en: "run", fr: "courir" },
  { en: "ran", fr: "a couru" },
  { en: "walk", fr: "marcher" },
  { en: "walked", fr: "a marché" },
  { en: "drive", fr: "conduire" },
  { en: "drove", fr: "a conduit" },
  { en: "fly", fr: "voler" },
  { en: "flew", fr: "a volé" },
  { en: "read", fr: "lire" },
  { en: "write", fr: "écrire" },
  { en: "wrote", fr: "a écrit" },
  { en: "learn", fr: "apprendre" },
  { en: "teach", fr: "enseigner" },
  { en: "understand", fr: "comprendre" },
  { en: "understood", fr: "a compris" },
  { en: "remember", fr: "se souvenir" },
  { en: "forget", fr: "oublier" },
  { en: "believe", fr: "croire" },
  { en: "feel", fr: "sentir" },
  { en: "felt", fr: "a senti" },
  { en: "man", fr: "homme" },
  { en: "woman", fr: "femme" },
  { en: "boy", fr: "garçon" },
  { en: "girl", fr: "fille" },
  { en: "child", fr: "enfant" },
  { en: "children", fr: "enfants" },
  { en: "baby", fr: "bébé" },
  { en: "father", fr: "père" },
  { en: "mother", fr: "mère" },
  { en: "dad", fr: "papa" },
  { en: "mom", fr: "maman" },
  { en: "son", fr: "fils" },
  { en: "daughter", fr: "fille" },
  { en: "brother", fr: "frère" },
  { en: "sister", fr: "sœur" },
  { en: "friend", fr: "ami" },
  { en: "friends", fr: "amis" },
  { en: "family", fr: "famille" },
  { en: "people", fr: "gens" },
  { en: "person", fr: "personne" },
  { en: "name", fr: "nom" },
  { en: "house", fr: "maison" },
  { en: "home", fr: "maison" },
  { en: "room", fr: "chambre" },
  { en: "door", fr: "porte" },
  { en: "window", fr: "fenêtre" },
  { en: "school", fr: "école" },
  { en: "work", fr: "travail" },
  { en: "job", fr: "travail" },
  { en: "car", fr: "voiture" },
  { en: "bus", fr: "bus" },
  { en: "train", fr: "train" },
  { en: "plane", fr: "avion" },
  { en: "boat", fr: "bateau" },
  { en: "road", fr: "route" },
  { en: "street", fr: "rue" },
  { en: "city", fr: "ville" },
  { en: "country", fr: "pays" },
  { en: "world", fr: "monde" },
  { en: "water", fr: "eau" },
  { en: "fire", fr: "feu" },
  { en: "air", fr: "air" },
  { en: "earth", fr: "terre" },
  { en: "sun", fr: "soleil" },
  { en: "moon", fr: "lune" },
  { en: "star", fr: "étoile" },
  { en: "sky", fr: "ciel" },
  { en: "rain", fr: "pluie" },
  { en: "snow", fr: "neige" },
  { en: "wind", fr: "vent" },
  { en: "tree", fr: "arbre" },
  { en: "flower", fr: "fleur" },
  { en: "animal", fr: "animal" },
  { en: "dog", fr: "chien" },
  { en: "cat", fr: "chat" },
  { en: "fish", fr: "poisson" },
  { en: "bird", fr: "oiseau" },
  { en: "horse", fr: "cheval" },
  { en: "food", fr: "nourriture" },
  { en: "rice", fr: "riz" },
  { en: "bread", fr: "pain" },
  { en: "meat", fr: "viande" },
  { en: "chicken", fr: "poulet" },
  { en: "egg", fr: "œuf" },
  { en: "milk", fr: "lait" },
  { en: "tea", fr: "thé" },
  { en: "coffee", fr: "café" },
  { en: "beer", fr: "bière" },
  { en: "wine", fr: "vin" },
  { en: "money", fr: "argent" },
  { en: "book", fr: "livre" },
  { en: "phone", fr: "téléphone" },
  { en: "computer", fr: "ordinateur" },
  { en: "table", fr: "table" },
  { en: "chair", fr: "chaise" },
  { en: "bed", fr: "lit" },
  { en: "time", fr: "temps" },
  { en: "day", fr: "jour" },
  { en: "night", fr: "nuit" },
  { en: "week", fr: "semaine" },
  { en: "month", fr: "mois" },
  { en: "year", fr: "année" },
  { en: "today", fr: "aujourd'hui" },
  { en: "tomorrow", fr: "demain" },
  { en: "yesterday", fr: "hier" },
  { en: "morning", fr: "matin" },
  { en: "afternoon", fr: "après-midi" },
  { en: "evening", fr: "soir" },
  { en: "love", fr: "amour" },
  { en: "life", fr: "vie" },
  { en: "death", fr: "mort" },
  { en: "war", fr: "guerre" },
  { en: "peace", fr: "paix" },
  { en: "god", fr: "dieu" },
  { en: "good", fr: "bon" },
  { en: "bad", fr: "mauvais" },
  { en: "big", fr: "grand" },
  { en: "small", fr: "petit" },
  { en: "new", fr: "nouveau" },
  { en: "old", fr: "vieux" },
  { en: "hot", fr: "chaud" },
  { en: "cold", fr: "froid" },
  { en: "fast", fr: "rapide" },
  { en: "slow", fr: "lent" },
  { en: "happy", fr: "heureux" },
  { en: "sad", fr: "triste" },
  { en: "angry", fr: "en colère" },
  { en: "tired", fr: "fatigué" },
  { en: "sick", fr: "malade" },
  { en: "beautiful", fr: "beau" },
  { en: "ugly", fr: "laid" },
  { en: "rich", fr: "riche" },
  { en: "poor", fr: "pauvre" },
  { en: "strong", fr: "fort" },
  { en: "weak", fr: "faible" },
  { en: "young", fr: "jeune" },
  { en: "easy", fr: "facile" },
  { en: "hard", fr: "difficile" },
  { en: "right", fr: "correct" },
  { en: "wrong", fr: "faux" },
  { en: "true", fr: "vrai" },
  { en: "false", fr: "faux" },
  { en: "same", fr: "même" },
  { en: "different", fr: "différent" },
  { en: "many", fr: "beaucoup" },
  { en: "much", fr: "beaucoup" },
  { en: "more", fr: "plus" },
  { en: "most", fr: "la plupart" },
  { en: "little", fr: "peu" },
  { en: "few", fr: "peu" },
  { en: "less", fr: "moins" },
  { en: "all", fr: "tout" },
  { en: "some", fr: "quelques" },
  { en: "no", fr: "aucun" },
  { en: "every", fr: "chaque" },
  { en: "very", fr: "très" },
  { en: "too", fr: "trop" },
  { en: "also", fr: "aussi" },
  { en: "and", fr: "et" },
  { en: "or", fr: "ou" },
  { en: "but", fr: "mais" },
  { en: "because", fr: "parce que" },
  { en: "so", fr: "donc" },
  { en: "if", fr: "si" },
  { en: "then", fr: "alors" },
  { en: "now", fr: "maintenant" },
  { en: "here", fr: "ici" },
  { en: "there", fr: "là" },
  { en: "not", fr: "ne pas" },
  { en: "only", fr: "seulement" },
  { en: "just", fr: "juste" },
  { en: "still", fr: "encore" },
  { en: "again", fr: "encore" },
  { en: "always", fr: "toujours" },
  { en: "never", fr: "jamais" },
  { en: "sometimes", fr: "parfois" },
  { en: "maybe", fr: "peut-être" },
  { en: "perhaps", fr: "peut-être" },
  { en: "one", fr: "un" },
  { en: "two", fr: "deux" },
  { en: "three", fr: "trois" },
  { en: "four", fr: "quatre" },
  { en: "five", fr: "cinq" },
  { en: "six", fr: "six" },
  { en: "seven", fr: "sept" },
  { en: "eight", fr: "huit" },
  { en: "nine", fr: "neuf" },
  { en: "ten", fr: "dix" },
  { en: "hundred", fr: "cent" },
  { en: "thousand", fr: "mille" },
  { en: "million", fr: "million" },
  { en: "how are you", fr: "comment allez-vous" },
  { en: "what is your name", fr: "comment tu t'appelles" },
  { en: "my name is", fr: "je m'appelle" },
  { en: "i don't know", fr: "je ne sais pas" },
  { en: "i don't understand", fr: "je ne comprends pas" },
  { en: "i love you", fr: "je t'aime" },
  { en: "i like you", fr: "tu me plais" },
  { en: "i miss you", fr: "tu me manques" },
  { en: "where is the bathroom", fr: "où sont les toilettes" },
  { en: "how much is it", fr: "combien ça coûte" },
  { en: "i am hungry", fr: "j'ai faim" },
  { en: "i am thirsty", fr: "j'ai soif" },
  { en: "i am tired", fr: "je suis fatigué" },
  { en: "see you later", fr: "à plus tard" },
  { en: "what time is it", fr: "quelle heure est-il" },
  // profanity
  { en: "fuck", fr: "baiser" },
  { en: "fucking", fr: "putain" },
  { en: "shit", fr: "merde" },
  { en: "bitch", fr: "salope" },
  { en: "ass", fr: "cul" },
  { en: "asshole", fr: "connard" },
  { en: "dick", fr: "bite" },
  { en: "pussy", fr: "chatte" },
  { en: "cock", fr: "bite" },
  { en: "damn", fr: "zut" },
  { en: "hell", fr: "enfer" },
  { en: "idiot", fr: "idiot" },
  { en: "stupid", fr: "stupide" },
  { en: "crazy", fr: "fou" },
  { en: "bastard", fr: "bâtard" },
  { en: "motherfucker", fr: "enculé" },
  { en: "bullshit", fr: "conneries" },
  { en: "fuck you", fr: "va te faire foutre" },
  { en: "go to hell", fr: "va au diable" },
  { en: "shut up", fr: "ta gueule" },
];
